// Generates roles.ts + roles.js + roles.json from roles/model.json.
// Mirrors the @eq-solutions/tokens build: one JSON source of truth, multiple
// generated artefacts. Run: `npm run build`.
//
// buildArtefacts(model) is pure (returns the artefact strings, throws on an
// invalid model) so roles.dist.test.ts can assert the committed files are not
// stale. The CLI section below is the only thing that touches the filesystem.

import { readFileSync, writeFileSync, realpathSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

/**
 * Validate the model and render the three artefacts.
 * @returns {{ json: string, ts: string, js: string, stats: { roles: number, permissions: number } }}
 */
export function buildArtefacts(model) {
  // ── validate ──────────────────────────────────────────────────────────────
  const roleKeys = model.roles.map((r) => r.key);
  const roleSet = new Set(roleKeys);
  const permKeys = model.permissions.map((p) => p.key);

  const errors = [];
  if (new Set(permKeys).size !== permKeys.length) errors.push('duplicate permission key(s)');
  if (new Set(roleKeys).size !== roleKeys.length) errors.push('duplicate role key(s)');
  for (const p of model.permissions) {
    for (const r of p.roles) if (!roleSet.has(r)) errors.push(`permission ${p.key} grants unknown role "${r}"`);
    if (!p.key.includes('.')) errors.push(`permission ${p.key} must be <module>.<verb>`);
  }
  if (errors.length) throw new Error('model.json invalid:\n  - ' + errors.join('\n  - '));

  // ── derive the matrix (per role -> perms that list it) ─────────────────────
  const matrix = Object.fromEntries(
    roleKeys.map((role) => [role, permKeys.filter((k) => model.permissions.find((p) => p.key === k).roles.includes(role))]),
  );

  // ── roles.json (resolved data, for server / non-TS consumers) ──────────────
  const resolved = {
    version: model.version,
    generated: true,
    roles: model.roles,
    roleKeys,
    tiers: model.tiers,
    platformAdmin: model.platformAdmin,
    modules: model.modules,
    permissions: model.permissions,
    matrix,
  };
  const json = JSON.stringify(resolved, null, 2) + '\n';

  // ── roles.ts (typed, the types consumable) ─────────────────────────────────
  const union = (xs) => xs.map((x) => `'${x}'`).join(' | ');
  const ts = `/* GENERATED by build.mjs from roles/model.json — do not edit. Run \`npm run build\`. */
/* @eq-solutions/roles v${model.version} — canonical EQ 5-tier role model + permission matrix.
 * Single source of truth across every EQ surface (Shell, Field, Service, Cards, Quotes).
 * Identity (role) is separate from billing (tier) and from the is_platform_admin override. */

export type EqRole = ${union(roleKeys)};
export type EqTier = ${union(model.tiers)};
export type PermKey = ${union(permKeys)};
export type ModuleKey = ${union(model.modules)};

export interface RoleMeta { key: EqRole; label: string; rank: number; description: string; }
export interface PermissionMeta { key: PermKey; module: ModuleKey; description: string; roles: readonly EqRole[]; }

export const ROLE_KEYS = [${roleKeys.map((r) => `'${r}'`).join(', ')}] as const satisfies readonly EqRole[];
export const TIERS = [${model.tiers.map((t) => `'${t}'`).join(', ')}] as const satisfies readonly EqTier[];

export const ROLES: readonly RoleMeta[] = ${JSON.stringify(model.roles)};
export const PERMISSIONS: readonly PermissionMeta[] = ${JSON.stringify(model.permissions)};

/** Field on the user/JWT that, when true, grants every permission across every tenant. */
export const PLATFORM_ADMIN_FIELD = '${model.platformAdmin.field}' as const;

/** Per-role permission grants. No inheritance — every grant is explicit. */
export const MATRIX: Record<EqRole, readonly PermKey[]> = ${JSON.stringify(matrix, null, 2)};

const MATRIX_SETS: Record<EqRole, Set<PermKey>> = Object.fromEntries(
  (Object.keys(MATRIX) as EqRole[]).map((r) => [r, new Set(MATRIX[r])]),
) as Record<EqRole, Set<PermKey>>;

/** Does this role hold this permission? is_platform_admin short-circuits to true. */
export function can(role: EqRole, perm: PermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return MATRIX_SETS[role]?.has(perm) ?? false;
}

/** All permissions a role holds (platform admins hold every PermKey). */
export function permissionsFor(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly PermKey[] {
  if (opts?.isPlatformAdmin) return PERMISSIONS.map((p) => p.key);
  return MATRIX[role] ?? [];
}

export function canAny(role: EqRole, perms: readonly PermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => MATRIX_SETS[role]?.has(p));
}

export function canAll(role: EqRole, perms: readonly PermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => MATRIX_SETS[role]?.has(p));
}

export function isEqRole(x: unknown): x is EqRole { return typeof x === 'string' && (ROLE_KEYS as readonly string[]).includes(x); }
`;

  // ── roles.js (runtime ESM, the entry consumers actually load) ──────────────
  // Tarball installs (github:eq-solutions/eq-roles#vX) do NOT run `build`, so the
  // committed .js IS the shipped runtime. It must inline its data — importing
  // roles.json would need an import attribute Netlify's bundler can't satisfy
  // (ERR_IMPORT_ASSERTION_TYPE_MISSING), and a raw .ts entry crashes the loader
  // (ERR_UNKNOWN_FILE_EXTENSION). Types live in roles.ts; logic is kept identical.
  const js = `/* GENERATED by build.mjs from roles/model.json — do not edit. Run \`npm run build\`. */
/* @eq-solutions/roles v${model.version} — runtime ESM entry (data inlined, types stripped).
 * Loaded by runtime consumers: Netlify function bundlers, plain Node ESM, RLS scripts.
 * Type declarations live in roles.ts; both are generated from roles/model.json. */

export const ROLE_KEYS = [${roleKeys.map((r) => `'${r}'`).join(', ')}];
export const TIERS = [${model.tiers.map((t) => `'${t}'`).join(', ')}];

export const ROLES = ${JSON.stringify(model.roles)};
export const PERMISSIONS = ${JSON.stringify(model.permissions)};

/** Field on the user/JWT that, when true, grants every permission across every tenant. */
export const PLATFORM_ADMIN_FIELD = '${model.platformAdmin.field}';

/** Per-role permission grants. No inheritance — every grant is explicit. */
export const MATRIX = ${JSON.stringify(matrix, null, 2)};

const MATRIX_SETS = Object.fromEntries(
  Object.keys(MATRIX).map((r) => [r, new Set(MATRIX[r])]),
);

/** Does this role hold this permission? is_platform_admin short-circuits to true. */
export function can(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return MATRIX_SETS[role]?.has(perm) ?? false;
}

/** All permissions a role holds (platform admins hold every PermKey). */
export function permissionsFor(role, opts) {
  if (opts?.isPlatformAdmin) return PERMISSIONS.map((p) => p.key);
  return MATRIX[role] ?? [];
}

export function canAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => MATRIX_SETS[role]?.has(p));
}

export function canAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => MATRIX_SETS[role]?.has(p));
}

export function isEqRole(x) { return typeof x === 'string' && ROLE_KEYS.includes(x); }
`;

  return { json, ts, js, stats: { roles: roleKeys.length, permissions: permKeys.length } };
}

// ── CLI: read the model, write the artefacts (only when run directly) ────────
const invokedDirectly = process.argv[1] && realpathSync(fileURLToPath(import.meta.url)) === realpathSync(process.argv[1]);
if (invokedDirectly) {
  const model = JSON.parse(readFileSync(join(here, 'roles', 'model.json'), 'utf8'));
  let artefacts;
  try {
    artefacts = buildArtefacts(model);
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
  writeFileSync(join(here, 'roles.json'), artefacts.json);
  writeFileSync(join(here, 'roles.ts'), artefacts.ts);
  writeFileSync(join(here, 'roles.js'), artefacts.js);
  console.log(`@eq-solutions/roles v${model.version} built: ${artefacts.stats.roles} roles, ${artefacts.stats.permissions} permissions -> roles.ts + roles.js + roles.json`);
}
