// Generates roles.ts + roles.json from roles/model.json.
// Mirrors the @eq-solutions/tokens build: one JSON source of truth, multiple
// generated artefacts. Run: `npm run build`.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const model = JSON.parse(readFileSync(join(here, 'roles', 'model.json'), 'utf8'));

// ── validate ────────────────────────────────────────────────────────────────
const roleKeys = model.roles.map((r) => r.key);
const roleSet = new Set(roleKeys);
const permKeys = model.permissions.map((p) => p.key);

const errors = [];
if (new Set(permKeys).size !== permKeys.length) errors.push('duplicate permission key(s)');
if (new Set(roleKeys).size !== roleKeys.length) errors.push('duplicate role key(s)');
for (const p of model.permissions) {
  for (const r of p.roles) if (!roleSet.has(r)) errors.push(`permission ${p.key} grants unknown role "${r}"`);
  if (!p.key.includes('.')) errors.push(`permission ${p.key} must be <module>.<verb>`);
}
if (errors.length) {
  console.error('model.json invalid:\n  - ' + errors.join('\n  - '));
  process.exit(1);
}

// ── derive the matrix (per role -> perms that list it) ───────────────────────
const matrix = Object.fromEntries(
  roleKeys.map((role) => [role, permKeys.filter((k) => model.permissions.find((p) => p.key === k).roles.includes(role))]),
);

// ── roles.json (resolved data, for server / non-TS consumers) ────────────────
const resolved = {
  version: model.version,
  generated: true,
  roles: model.roles,
  roleKeys,
  tiers: model.tiers,
  platformAdmin: model.platformAdmin,
  modules: model.modules,
  permissions: model.permissions,
  matrix,
};
writeFileSync(join(here, 'roles.json'), JSON.stringify(resolved, null, 2) + '\n');

// ── roles.ts (typed, the primary consumable) ─────────────────────────────────
const union = (xs) => xs.map((x) => `'${x}'`).join(' | ');
const ts = `/* GENERATED by build.mjs from roles/model.json — do not edit. Run \`npm run build\`. */
/* @eq-solutions/roles v${model.version} — canonical EQ 5-tier role model + permission matrix.
 * Single source of truth across every EQ surface (Shell, Field, Service, Cards, Quotes).
 * Identity (role) is separate from billing (tier) and from the is_platform_admin override. */

export type EqRole = ${union(roleKeys)};
export type EqTier = ${union(model.tiers)};
export type PermKey = ${union(permKeys)};
export type ModuleKey = ${union(model.modules)};

export interface RoleMeta { key: EqRole; label: string; rank: number; description: string; }
export interface PermissionMeta { key: PermKey; module: ModuleKey; description: string; roles: readonly EqRole[]; }

export const ROLE_KEYS = [${roleKeys.map((r) => `'${r}'`).join(', ')}] as const satisfies readonly EqRole[];
export const TIERS = [${model.tiers.map((t) => `'${t}'`).join(', ')}] as const satisfies readonly EqTier[];

export const ROLES: readonly RoleMeta[] = ${JSON.stringify(model.roles)};
export const PERMISSIONS: readonly PermissionMeta[] = ${JSON.stringify(model.permissions)};

/** Field on the user/JWT that, when true, grants every permission across every tenant. */
export const PLATFORM_ADMIN_FIELD = '${model.platformAdmin.field}' as const;

/** Per-role permission grants. No inheritance — every grant is explicit. */
export const MATRIX: Record<EqRole, readonly PermKey[]> = ${JSON.stringify(matrix, null, 2)};

const MATRIX_SETS: Record<EqRole, Set<PermKey>> = Object.fromEntries(
  (Object.keys(MATRIX) as EqRole[]).map((r) => [r, new Set(MATRIX[r])]),
) as Record<EqRole, Set<PermKey>>;

/** Does this role hold this permission? is_platform_admin short-circuits to true. */
export function can(role: EqRole, perm: PermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return MATRIX_SETS[role]?.has(perm) ?? false;
}

/** All permissions a role holds (platform admins hold every PermKey). */
export function permissionsFor(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly PermKey[] {
  if (opts?.isPlatformAdmin) return PERMISSIONS.map((p) => p.key);
  return MATRIX[role] ?? [];
}

export function canAny(role: EqRole, perms: readonly PermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => MATRIX_SETS[role]?.has(p));
}

export function canAll(role: EqRole, perms: readonly PermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => MATRIX_SETS[role]?.has(p));
}

export function isEqRole(x: unknown): x is EqRole { return typeof x === 'string' && (ROLE_KEYS as readonly string[]).includes(x); }
`;
writeFileSync(join(here, 'roles.ts'), ts);

console.log(`@eq-solutions/roles v${model.version} built: ${roleKeys.length} roles, ${permKeys.length} permissions -> roles.ts + roles.json`);
