/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles v1.0.0 — canonical EQ 5-tier role model + permission matrix.
 * Single source of truth across every EQ surface (Shell, Field, Service, Cards, Quotes).
 * Identity (role) is separate from billing (tier) and from the is_platform_admin override. */

export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire';
export type EqTier = 'trial' | 'standard' | 'advanced' | 'enterprise';
export type PermKey = 'admin.list_users' | 'admin.invite_user' | 'admin.edit_user' | 'admin.deactivate_user' | 'admin.review_cards' | 'audit.view' | 'audit.rollback' | 'intake.view' | 'intake.import' | 'intake.commit' | 'equipment.view' | 'equipment.edit' | 'reports.view' | 'reports.upload' | 'reports.generate_briefing';
export type ModuleKey = 'admin' | 'audit' | 'intake' | 'equipment' | 'reports';

export interface RoleMeta { key: EqRole; label: string; rank: number; description: string; }
export interface PermissionMeta { key: PermKey; module: ModuleKey; description: string; roles: readonly EqRole[]; }

export const ROLE_KEYS = ['manager', 'supervisor', 'employee', 'apprentice', 'labour_hire'] as const satisfies readonly EqRole[];
export const TIERS = ['trial', 'standard', 'advanced', 'enterprise'] as const satisfies readonly EqTier[];

export const ROLES: readonly RoleMeta[] = [{"key":"manager","label":"Manager","rank":1,"description":"Full admin — user management, audit view + rollback, every module action."},{"key":"supervisor","label":"Supervisor","rank":2,"description":"Audit view, intake commit, equipment edit. No user management."},{"key":"employee","label":"Employee","rank":3,"description":"Intake view + import, equipment view. No commit, no admin."},{"key":"apprentice","label":"Apprentice","rank":4,"description":"Read-mostly — intake view only."},{"key":"labour_hire","label":"Labour Hire","rank":5,"description":"Minimal — own roster / timesheet only (no shell permissions today)."}];
export const PERMISSIONS: readonly PermissionMeta[] = [{"key":"admin.list_users","module":"admin","description":"List tenant users.","roles":["manager"]},{"key":"admin.invite_user","module":"admin","description":"Invite a new user to the tenant.","roles":["manager"]},{"key":"admin.edit_user","module":"admin","description":"Edit a user's role / details.","roles":["manager"]},{"key":"admin.deactivate_user","module":"admin","description":"Deactivate a user.","roles":["manager"]},{"key":"admin.review_cards","module":"admin","description":"Review Cards onboarding submissions.","roles":["manager"]},{"key":"audit.view","module":"audit","description":"View the audit log.","roles":["manager","supervisor"]},{"key":"audit.rollback","module":"audit","description":"Roll back an audited change.","roles":["manager"]},{"key":"intake.view","module":"intake","description":"See the Intake surface.","roles":["manager","supervisor","employee","apprentice"]},{"key":"intake.import","module":"intake","description":"Initiate an import (drop file, map, validate).","roles":["manager","supervisor","employee"]},{"key":"intake.commit","module":"intake","description":"Commit a validated batch to canonical (destructive).","roles":["manager","supervisor"]},{"key":"equipment.view","module":"equipment","description":"See the Plant & Equipment list + calibration.","roles":["manager","supervisor","employee"]},{"key":"equipment.edit","module":"equipment","description":"Add / edit equipment + calibration fields.","roles":["manager","supervisor"]},{"key":"reports.view","module":"reports","description":"View GM reports.","roles":["manager"]},{"key":"reports.upload","module":"reports","description":"Upload a source report.","roles":["manager"]},{"key":"reports.generate_briefing","module":"reports","description":"Generate the AI briefing.","roles":["manager"]}];

/** Field on the user/JWT that, when true, grants every permission across every tenant. */
export const PLATFORM_ADMIN_FIELD = 'is_platform_admin' as const;

/** Per-role permission grants. No inheritance — every grant is explicit. */
export const MATRIX: Record<EqRole, readonly PermKey[]> = {
  "manager": [
    "admin.list_users",
    "admin.invite_user",
    "admin.edit_user",
    "admin.deactivate_user",
    "admin.review_cards",
    "audit.view",
    "audit.rollback",
    "intake.view",
    "intake.import",
    "intake.commit",
    "equipment.view",
    "equipment.edit",
    "reports.view",
    "reports.upload",
    "reports.generate_briefing"
  ],
  "supervisor": [
    "audit.view",
    "intake.view",
    "intake.import",
    "intake.commit",
    "equipment.view",
    "equipment.edit"
  ],
  "employee": [
    "intake.view",
    "intake.import",
    "equipment.view"
  ],
  "apprentice": [
    "intake.view"
  ],
  "labour_hire": []
};

const MATRIX_SETS: Record<EqRole, Set<PermKey>> = Object.fromEntries(
  (Object.keys(MATRIX) as EqRole[]).map((r) => [r, new Set(MATRIX[r])]),
) as Record<EqRole, Set<PermKey>>;

/** Does this role hold this permission? is_platform_admin short-circuits to true. */
export function can(role: EqRole, perm: PermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return MATRIX_SETS[role]?.has(perm) ?? false;
}

/** All permissions a role holds (platform admins hold every PermKey). */
export function permissionsFor(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly PermKey[] {
  if (opts?.isPlatformAdmin) return PERMISSIONS.map((p) => p.key);
  return MATRIX[role] ?? [];
}

export function isEqRole(x: unknown): x is EqRole { return typeof x === 'string' && (ROLE_KEYS as readonly string[]).includes(x); }
