// GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`.
// @eq-solutions/roles v2.5.0 — canonical EQ 6-tier role model + permission matrix (Dart).
// Mirrors roles.ts / roles.js exactly. Single source of truth across every EQ
// surface (Shell, Field, Service, Cards, Quotes). Identity (role) is separate
// from billing (tier) and from the isPlatformAdmin override.
//
// Requires Dart 2.17+ (enhanced enums — EqRole.value carries the exact wire
// string read from JWT app_metadata.eq_role). No external package dependency.

/// Canonical EQ role. `.value` is the exact wire string (JWT app_metadata.eq_role).
enum EqRole {
  manager('manager', 'Manager', 1, 'Full admin — user management, audit view + rollback, every module action.'),
  supervisor('supervisor', 'Supervisor', 2, 'Audit view, intake commit, equipment edit. No user management.'),
  employee('employee', 'Employee', 3, 'Intake view + import, equipment view. No commit, no admin.'),
  apprentice('apprentice', 'Apprentice', 4, 'Read-mostly — intake + equipment view.'),
  labourHire('labour_hire', 'Labour Hire', 5, 'Minimal — own roster / timesheet only (no shell permissions today).'),
  subcontractor('subcontractor', 'Subcontractor', 6, 'External trade engaged for a job, not an agency worker. Minimal — same baseline as labour_hire.');

  const EqRole(this.value, this.label, this.rank, this.description);

  /// Wire value — matches the DB enum / JWT claim exactly (e.g. 'labour_hire').
  final String value;
  /// Short plain-English name for admin UIs.
  final String label;
  final int rank;
  final String description;

  /// Parse a wire role string (JWT app_metadata.eq_role). Returns null for unknown.
  static EqRole? fromValue(String? value) {
    for (final r in EqRole.values) {
      if (r.value == value) return r;
    }
    return null;
  }
}

const List<String> kTiers = ['trial', 'standard', 'advanced', 'enterprise'];

/// Field on the user/JWT that, when true, grants every permission across every tenant.
const String kPlatformAdminField = 'is_platform_admin';

/// Permission metadata. `deprecated` (if set) explains why + the replacement —
/// still enforced/emitted, just don't grant it to new consumers.
class PermissionMeta {
  const PermissionMeta(this.key, this.module, this.label, this.description, this.roles, {this.deprecated});
  final String key;
  final String module;
  final String label;
  final String description;
  final Set<EqRole> roles;
  final String? deprecated;
}

const List<PermissionMeta> kPermissions = [
  PermissionMeta('admin.list_users', 'admin', 'View users', 'List tenant users.', {EqRole.manager}),
  PermissionMeta('admin.invite_user', 'admin', 'Invite users', 'Invite a new user to the tenant.', {EqRole.manager}),
  PermissionMeta('admin.edit_user', 'admin', 'Edit users', 'Edit a user\'s role / details.', {EqRole.manager}),
  PermissionMeta('admin.deactivate_user', 'admin', 'Deactivate users', 'Deactivate a user.', {EqRole.manager}),
  PermissionMeta('admin.review_cards', 'admin', 'Review onboarding', 'Review Cards onboarding submissions.', {EqRole.manager}),
  PermissionMeta('admin.manage_groups', 'admin', 'Manage access groups', 'Create and manage security groups + membership.', {EqRole.manager}),
  PermissionMeta('audit.view', 'audit', 'View activity log', 'View the audit log.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('audit.rollback', 'audit', 'Undo changes', 'Roll back an audited change.', {EqRole.manager}),
  PermissionMeta('entity.view', 'entity', 'View records', 'View canonical records (customers, sites, contacts, assets).', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice}),
  PermissionMeta('entity.create', 'entity', 'Add records', 'Create a new canonical record.', {EqRole.manager}),
  PermissionMeta('entity.edit', 'entity', 'Edit records', 'Edit an existing canonical record.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('entity.delete', 'entity', 'Delete records', 'Delete a canonical record (hard delete, manager-only).', {EqRole.manager}),
  PermissionMeta('intake.view', 'intake', 'View imports', 'See the Intake surface.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice}),
  PermissionMeta('intake.import', 'intake', 'Start an import', 'Initiate an import (drop file, map, validate).', {EqRole.manager, EqRole.supervisor, EqRole.employee}),
  PermissionMeta('intake.commit', 'intake', 'Confirm an import', 'Commit a validated batch to canonical (destructive).', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('equipment.view', 'equipment', 'View equipment', 'See the Plant & Equipment list + calibration.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice}),
  PermissionMeta('equipment.edit', 'equipment', 'Edit equipment', 'Add / edit equipment + calibration fields.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('reports.view', 'reports', 'View reports', 'View GM reports.', {EqRole.manager}),
  PermissionMeta('reports.upload', 'reports', 'Upload reports', 'Upload a source report.', {EqRole.manager}),
  PermissionMeta('reports.generate_briefing', 'reports', 'Generate AI briefing', 'Generate the AI briefing.', {EqRole.manager}),
  PermissionMeta('cards.view', 'cards', 'Open Cards', 'Access the Cards onboarding surface.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice}, deprecated: 'Cards is a worker-facing app gated by tenant entitlement (org_module_entitlements.cards), not a per-user employer permission. Kept for existing tenant_role_overrides; do not grant to new consumers. Replacement: entitlement check.'),
  PermissionMeta('cards.onboard', 'cards', 'Submit onboarding', 'Submit or manage an onboarding card.', {EqRole.manager, EqRole.supervisor}, deprecated: 'Duplicates admin.review_cards (the real employer-side \'review Cards onboarding\' gate, already in use). Kept for existing tenant_role_overrides; do not grant to new consumers. Replacement: admin.review_cards.'),
  PermissionMeta('service.view', 'service', 'View maintenance', 'View the Service CMMS (work orders, defects, PPM).', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice}),
  PermissionMeta('service.create', 'service', 'Raise work orders', 'Create a work order or defect.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('service.close', 'service', 'Close work orders', 'Close / resolve a work order.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('field.view', 'field', 'View field resources', 'View Field resources — staff, licences, availability, assignments.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice, EqRole.labourHire, EqRole.subcontractor}),
  PermissionMeta('field.dispatch', 'field', 'Dispatch staff', 'Dispatch staff to jobs / shifts.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('quotes.view', 'quotes', 'View quotes', 'View quotes.', {EqRole.manager, EqRole.supervisor, EqRole.employee}),
  PermissionMeta('quotes.create', 'quotes', 'Create quotes', 'Create or edit a quote.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('quotes.approve', 'quotes', 'Approve quotes', 'Approve and send a quote.', {EqRole.manager}),
];

/// Per-role permission grants. No inheritance — every grant is explicit.
final Map<EqRole, Set<String>> kMatrix = {
    EqRole.manager: ['admin.list_users', 'admin.invite_user', 'admin.edit_user', 'admin.deactivate_user', 'admin.review_cards', 'admin.manage_groups', 'audit.view', 'audit.rollback', 'entity.view', 'entity.create', 'entity.edit', 'entity.delete', 'intake.view', 'intake.import', 'intake.commit', 'equipment.view', 'equipment.edit', 'reports.view', 'reports.upload', 'reports.generate_briefing', 'cards.view', 'cards.onboard', 'service.view', 'service.create', 'service.close', 'field.view', 'field.dispatch', 'quotes.view', 'quotes.create', 'quotes.approve'].toSet(),
    EqRole.supervisor: ['audit.view', 'entity.view', 'entity.edit', 'intake.view', 'intake.import', 'intake.commit', 'equipment.view', 'equipment.edit', 'cards.view', 'cards.onboard', 'service.view', 'service.create', 'service.close', 'field.view', 'field.dispatch', 'quotes.view', 'quotes.create'].toSet(),
    EqRole.employee: ['entity.view', 'intake.view', 'intake.import', 'equipment.view', 'cards.view', 'service.view', 'field.view', 'quotes.view'].toSet(),
    EqRole.apprentice: ['entity.view', 'intake.view', 'equipment.view', 'cards.view', 'service.view', 'field.view'].toSet(),
    EqRole.labourHire: ['field.view'].toSet(),
    EqRole.subcontractor: ['field.view'].toSet(),
};

/// Does this role hold this permission? isPlatformAdmin short-circuits to true.
bool can(EqRole role, String perm, {bool isPlatformAdmin = false}) {
  if (isPlatformAdmin) return true;
  return kMatrix[role]?.contains(perm) ?? false;
}

/// All permissions a role holds (platform admins hold every key).
Set<String> permissionsFor(EqRole role, {bool isPlatformAdmin = false}) {
  if (isPlatformAdmin) return kPermissions.map((p) => p.key).toSet();
  return kMatrix[role] ?? <String>{};
}

final Map<String, String> _kPermLabels = {
  for (final p in kPermissions) p.key: p.label,
};
/// Plain-English label for a permission key — what a non-technical manager reads.
String? labelFor(String perm) => _kPermLabels[perm];

/// Canonical starter security-group template — an ADDITIVE bundle of extra
/// perms on top of a user's base role. Not a role.
class DefaultGroup {
  const DefaultGroup(this.key, this.name, this.description, this.perms);
  final String key;
  final String name;
  final String description;
  final List<String> perms;
}

const List<DefaultGroup> kDefaultGroups = [
  DefaultGroup('equipment_editors', 'Equipment editors', 'Edit the plant & equipment list and calibration details. Add people here who maintain equipment but whose role normally only lets them view it.', ['equipment.view', 'equipment.edit']),
  DefaultGroup('report_viewers', 'Report viewers', 'View GM reports without being made a manager. Add supervisors or leads here who need to read reports.', ['reports.view']),
  DefaultGroup('project_managers', 'Project Managers', 'Manage users, review Cards onboarding, and view the audit log without full manager admin rights. Promoted from a tenant-specific group (originally SKS) once it proved to be a common cross-cutting need, not a one-off.', ['admin.list_users', 'admin.edit_user', 'admin.review_cards', 'audit.view'])
];

/// Combine a role's base grants with EXTRA perms from security-group
/// memberships into the effective set used for a UI/authZ decision.
/// isPlatformAdmin short-circuits to every permission. revokes (reserved for
/// future per-user denials) is applied last, deny-wins.
Set<String> resolveEffectivePermissions({
  required EqRole role,
  Set<String> groupPerms = const {},
  bool isPlatformAdmin = false,
  Set<String> revokes = const {},
}) {
  if (isPlatformAdmin) return kPermissions.map((p) => p.key).toSet();
  final permKeys = kPermissions.map((p) => p.key).toSet();
  final granted = <String>{...(kMatrix[role] ?? <String>{})};
  for (final p in groupPerms) {
    if (permKeys.contains(p)) granted.add(p);
  }
  granted.removeAll(revokes);
  return granted;
}

/// EQ Service (CMMS) tenant_members.role -> canonical EqRole. super_admin maps to a tenant-scoped manager (NOT is_platform_admin); supervisor is a direct match; technician is an employee; read_only is a read-mostly apprentice.
const Map<String, EqRole> kServiceRoleMap = {
  'super_admin': EqRole.manager,
  'admin': EqRole.manager,
  'supervisor': EqRole.supervisor,
  'technician': EqRole.employee,
  'read_only': EqRole.apprentice,
};

/// Map a service role onto canonical EqRole. Returns null for unknown input.
EqRole? fromServiceRole(String? role) => kServiceRoleMap[role];
