/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/admin v2.7.0 — admin-module permission slice.
 * Import from "@eq-solutions/roles/admin" for typed admin.* perms only.
 * Full 60-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type AdminPermKey = 'admin.list_users' | 'admin.invite_user' | 'admin.edit_user' | 'admin.deactivate_user' | 'admin.review_cards' | 'admin.manage_groups' | 'admin.assign_role' | 'admin.delete_user';
export const ADMIN_PERM_KEYS: readonly AdminPermKey[] = ['admin.list_users', 'admin.invite_user', 'admin.edit_user', 'admin.deactivate_user', 'admin.review_cards', 'admin.manage_groups', 'admin.assign_role', 'admin.delete_user'];
export const ADMIN_PERMISSIONS = [{"key":"admin.list_users","module":"admin","label":"View users","description":"See everyone who can sign in to your organisation, with their role and status.","roles":["manager"]},{"key":"admin.invite_user","module":"admin","label":"Invite users","description":"Send someone an invitation to join and set up their sign-in.","roles":["manager"]},{"key":"admin.edit_user","module":"admin","label":"Edit users","description":"Change someone's name or contact details. Changing their role or permanently deleting them are their own separate permissions.","roles":["manager"]},{"key":"admin.deactivate_user","module":"admin","label":"Deactivate users","description":"Switch off someone’s access so they can no longer sign in. Their records are kept.","roles":["manager"]},{"key":"admin.review_cards","module":"admin","label":"Review onboarding","description":"Review and approve the details a new worker submits when they join, before they're added as staff.","roles":["manager"]},{"key":"admin.manage_groups","module":"admin","label":"Manage access groups","description":"Create access groups and choose who belongs to them. Groups add permissions on top of someone’s role.","roles":["manager"]},{"key":"admin.assign_role","module":"admin","label":"Change someone's role","description":"Set or change what role a person holds — wherever that happens, including through EQ Cards.","roles":["manager"]},{"key":"admin.delete_user","module":"admin","label":"Permanently delete a user","description":"Permanently delete a person's account. This cannot be undone.","roles":["manager"]}] as const;

/** Per-role grants within the admin module. */
export const ADMIN_MATRIX: Record<EqRole, readonly AdminPermKey[]> = {
  "manager": [
    "admin.list_users",
    "admin.invite_user",
    "admin.edit_user",
    "admin.deactivate_user",
    "admin.review_cards",
    "admin.manage_groups",
    "admin.assign_role",
    "admin.delete_user"
  ],
  "supervisor": [],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _ADMIN_SETS: Record<EqRole, Set<AdminPermKey>> = Object.fromEntries(
  (Object.keys(ADMIN_MATRIX) as EqRole[]).map((r) => [r, new Set(ADMIN_MATRIX[r])]),
) as Record<EqRole, Set<AdminPermKey>>;

export function adminCan(role: EqRole, perm: AdminPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _ADMIN_SETS[role]?.has(perm) ?? false;
}

export function permissionsForAdmin(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly AdminPermKey[] {
  if (opts?.isPlatformAdmin) return ADMIN_PERM_KEYS.slice();
  return ADMIN_MATRIX[role] ?? [];
}

export function adminCanAny(role: EqRole, perms: readonly AdminPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _ADMIN_SETS[role]?.has(p));
}

export function adminCanAll(role: EqRole, perms: readonly AdminPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _ADMIN_SETS[role]?.has(p));
}
