/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/admin v2.5.3 — admin-module permission slice.
 * Import from "@eq-solutions/roles/admin" for typed admin.* perms only.
 * Full 46-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type AdminPermKey = 'admin.list_users' | 'admin.invite_user' | 'admin.edit_user' | 'admin.deactivate_user' | 'admin.review_cards' | 'admin.manage_groups';
export const ADMIN_PERM_KEYS: readonly AdminPermKey[] = ['admin.list_users', 'admin.invite_user', 'admin.edit_user', 'admin.deactivate_user', 'admin.review_cards', 'admin.manage_groups'];
export const ADMIN_PERMISSIONS = [{"key":"admin.list_users","module":"admin","label":"View users","description":"List tenant users.","roles":["manager"]},{"key":"admin.invite_user","module":"admin","label":"Invite users","description":"Invite a new user to the tenant.","roles":["manager"]},{"key":"admin.edit_user","module":"admin","label":"Edit users","description":"Edit a user's role / details.","roles":["manager"]},{"key":"admin.deactivate_user","module":"admin","label":"Deactivate users","description":"Deactivate a user.","roles":["manager"]},{"key":"admin.review_cards","module":"admin","label":"Review onboarding","description":"Review Cards onboarding submissions.","roles":["manager"]},{"key":"admin.manage_groups","module":"admin","label":"Manage access groups","description":"Create and manage security groups + membership.","roles":["manager"]}] as const;

/** Per-role grants within the admin module. */
export const ADMIN_MATRIX: Record<EqRole, readonly AdminPermKey[]> = {
  "manager": [
    "admin.list_users",
    "admin.invite_user",
    "admin.edit_user",
    "admin.deactivate_user",
    "admin.review_cards",
    "admin.manage_groups"
  ],
  "supervisor": [],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _ADMIN_SETS: Record<EqRole, Set<AdminPermKey>> = Object.fromEntries(
  (Object.keys(ADMIN_MATRIX) as EqRole[]).map((r) => [r, new Set(ADMIN_MATRIX[r])]),
) as Record<EqRole, Set<AdminPermKey>>;

export function adminCan(role: EqRole, perm: AdminPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _ADMIN_SETS[role]?.has(perm) ?? false;
}

export function permissionsForAdmin(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly AdminPermKey[] {
  if (opts?.isPlatformAdmin) return ADMIN_PERM_KEYS.slice();
  return ADMIN_MATRIX[role] ?? [];
}

export function adminCanAny(role: EqRole, perms: readonly AdminPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _ADMIN_SETS[role]?.has(p));
}

export function adminCanAll(role: EqRole, perms: readonly AdminPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _ADMIN_SETS[role]?.has(p));
}
