/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/admin v2.6.0 — admin-module permission slice (runtime ESM). */

export const ADMIN_PERM_KEYS = ['admin.list_users', 'admin.invite_user', 'admin.edit_user', 'admin.deactivate_user', 'admin.review_cards', 'admin.manage_groups'];
export const ADMIN_PERMISSIONS = [{"key":"admin.list_users","module":"admin","label":"View users","description":"See everyone who can sign in to your organisation, with their role and status.","roles":["manager"]},{"key":"admin.invite_user","module":"admin","label":"Invite users","description":"Send someone an invitation to join and set up their sign-in.","roles":["manager"]},{"key":"admin.edit_user","module":"admin","label":"Edit users","description":"Change someone's role, name, or contact details.","roles":["manager"]},{"key":"admin.deactivate_user","module":"admin","label":"Deactivate users","description":"Switch off someone’s access so they can no longer sign in. Their records are kept.","roles":["manager"]},{"key":"admin.review_cards","module":"admin","label":"Review onboarding","description":"Review and approve the details new workers submit when they join — licences, contact details, and documents.","roles":["manager"]},{"key":"admin.manage_groups","module":"admin","label":"Manage access groups","description":"Create access groups and choose who belongs to them. Groups add permissions on top of someone’s role.","roles":["manager"]}];

/** Per-role grants within the admin module. */
export const ADMIN_MATRIX = {
  "manager": [
    "admin.list_users",
    "admin.invite_user",
    "admin.edit_user",
    "admin.deactivate_user",
    "admin.review_cards",
    "admin.manage_groups"
  ],
  "supervisor": [],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _ADMIN_SETS = Object.fromEntries(
  Object.keys(ADMIN_MATRIX).map((r) => [r, new Set(ADMIN_MATRIX[r])]),
);

export function adminCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _ADMIN_SETS[role]?.has(perm) ?? false;
}

export function permissionsForAdmin(role, opts) {
  if (opts?.isPlatformAdmin) return ADMIN_PERM_KEYS.slice();
  return ADMIN_MATRIX[role] ?? [];
}

export function adminCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _ADMIN_SETS[role]?.has(p));
}

export function adminCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _ADMIN_SETS[role]?.has(p));
}
