/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/ai v2.7.2 — ai-module permission slice (runtime ESM). */

export const AI_PERM_KEYS = ['ai.view_briefing', 'ai.use'];
export const AI_PERMISSIONS = [{"key":"ai.view_briefing","module":"ai","label":"View the daily briefing","description":"See the daily AI-written activity summary, and dismiss or mark your own action items done. Manager and supervisor only — the brief names workers alongside their licence numbers and expiry dates, and includes quote and pipeline dollar values.","roles":["manager","supervisor"]},{"key":"ai.use","module":"ai","label":"Use AI tools","description":"Use the AI assistant, ask questions about jobs and licences, and run licence-photo recognition.","roles":["manager","supervisor"]}];

/** Per-role grants within the ai module. */
export const AI_MATRIX = {
  "manager": [
    "ai.view_briefing",
    "ai.use"
  ],
  "supervisor": [
    "ai.view_briefing",
    "ai.use"
  ],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _AI_SETS = Object.fromEntries(
  Object.keys(AI_MATRIX).map((r) => [r, new Set(AI_MATRIX[r])]),
);

export function aiCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _AI_SETS[role]?.has(perm) ?? false;
}

export function permissionsForAi(role, opts) {
  if (opts?.isPlatformAdmin) return AI_PERM_KEYS.slice();
  return AI_MATRIX[role] ?? [];
}

export function aiCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _AI_SETS[role]?.has(p));
}

export function aiCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _AI_SETS[role]?.has(p));
}
