/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/audit v2.2.0 — audit-module permission slice.
 * Import from "@eq-solutions/roles/audit" for typed audit.* perms only.
 * Full 30-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire';

export type AuditPermKey = 'audit.view' | 'audit.rollback';
export const AUDIT_PERM_KEYS: readonly AuditPermKey[] = ['audit.view', 'audit.rollback'];
export const AUDIT_PERMISSIONS = [{"key":"audit.view","module":"audit","label":"View activity log","description":"View the audit log.","roles":["manager","supervisor"]},{"key":"audit.rollback","module":"audit","label":"Undo changes","description":"Roll back an audited change.","roles":["manager"]}] as const;

/** Per-role grants within the audit module. */
export const AUDIT_MATRIX: Record<EqRole, readonly AuditPermKey[]> = {
  "manager": [
    "audit.view",
    "audit.rollback"
  ],
  "supervisor": [
    "audit.view"
  ],
  "employee": [],
  "apprentice": [],
  "labour_hire": []
};

const _AUDIT_SETS: Record<EqRole, Set<AuditPermKey>> = Object.fromEntries(
  (Object.keys(AUDIT_MATRIX) as EqRole[]).map((r) => [r, new Set(AUDIT_MATRIX[r])]),
) as Record<EqRole, Set<AuditPermKey>>;

export function auditCan(role: EqRole, perm: AuditPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _AUDIT_SETS[role]?.has(perm) ?? false;
}

export function permissionsForAudit(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly AuditPermKey[] {
  if (opts?.isPlatformAdmin) return AUDIT_PERM_KEYS.slice();
  return AUDIT_MATRIX[role] ?? [];
}

export function auditCanAny(role: EqRole, perms: readonly AuditPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _AUDIT_SETS[role]?.has(p));
}

export function auditCanAll(role: EqRole, perms: readonly AuditPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _AUDIT_SETS[role]?.has(p));
}
