/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/audit v2.7.1 — audit-module permission slice (runtime ESM). */

export const AUDIT_PERM_KEYS = ['audit.view', 'audit.rollback'];
export const AUDIT_PERMISSIONS = [{"key":"audit.view","module":"audit","label":"View activity log","description":"See what changed, who changed it, and when.","roles":["manager","supervisor"]},{"key":"audit.rollback","module":"audit","label":"Undo changes","description":"Reverse a change shown in the activity log, putting the record back as it was.","roles":["manager"],"deprecated":"The undo action does not currently work — the system always refuses it. Kept only so nobody's existing access breaks; do not grant to anyone new. Bring this back once undo is rebuilt."}];

/** Per-role grants within the audit module. */
export const AUDIT_MATRIX = {
  "manager": [
    "audit.view",
    "audit.rollback"
  ],
  "supervisor": [
    "audit.view"
  ],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _AUDIT_SETS = Object.fromEntries(
  Object.keys(AUDIT_MATRIX).map((r) => [r, new Set(AUDIT_MATRIX[r])]),
);

export function auditCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _AUDIT_SETS[role]?.has(perm) ?? false;
}

export function permissionsForAudit(role, opts) {
  if (opts?.isPlatformAdmin) return AUDIT_PERM_KEYS.slice();
  return AUDIT_MATRIX[role] ?? [];
}

export function auditCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _AUDIT_SETS[role]?.has(p));
}

export function auditCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _AUDIT_SETS[role]?.has(p));
}
