/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/cards v2.6.0 — cards-module permission slice (runtime ESM). */

export const CARDS_PERM_KEYS = ['cards.view', 'cards.onboard'];
export const CARDS_PERMISSIONS = [{"key":"cards.view","module":"cards","label":"Open Cards","description":"Open the worker onboarding app.","roles":["manager","supervisor","employee","apprentice"],"deprecated":"No longer used. EQ Cards is switched on for a whole organisation rather than per person. Existing settings still work — do not apply this to anyone new."},{"key":"cards.onboard","module":"cards","label":"Submit onboarding","description":"Fill in or manage a worker’s onboarding details.","roles":["manager","supervisor"],"deprecated":"No longer used — “Review onboarding” does this job. Existing settings still work — do not apply this to anyone new."}];

/** Per-role grants within the cards module. */
export const CARDS_MATRIX = {
  "manager": [
    "cards.view",
    "cards.onboard"
  ],
  "supervisor": [
    "cards.view",
    "cards.onboard"
  ],
  "employee": [
    "cards.view"
  ],
  "apprentice": [
    "cards.view"
  ],
  "labour_hire": [],
  "subcontractor": []
};

const _CARDS_SETS = Object.fromEntries(
  Object.keys(CARDS_MATRIX).map((r) => [r, new Set(CARDS_MATRIX[r])]),
);

export function cardsCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _CARDS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForCards(role, opts) {
  if (opts?.isPlatformAdmin) return CARDS_PERM_KEYS.slice();
  return CARDS_MATRIX[role] ?? [];
}

export function cardsCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _CARDS_SETS[role]?.has(p));
}

export function cardsCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _CARDS_SETS[role]?.has(p));
}
