/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/documents v2.7.3 — documents-module permission slice.
 * Import from "@eq-solutions/roles/documents" for typed documents.* perms only.
 * Full 61-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type DocumentsPermKey = 'documents.view' | 'documents.manage' | 'documents.assign';
export const DOCUMENTS_PERM_KEYS: readonly DocumentsPermKey[] = ['documents.view', 'documents.manage', 'documents.assign'];
export const DOCUMENTS_PERMISSIONS = [{"key":"documents.view","module":"documents","label":"View documents","description":"See the document library, and the documents assigned to you to read or sign.","roles":["manager","supervisor","employee","apprentice","labour_hire","subcontractor"]},{"key":"documents.manage","module":"documents","label":"Manage documents","description":"Upload document versions, archive documents, and add, rename, or delete categories.","roles":["manager","supervisor"]},{"key":"documents.assign","module":"documents","label":"Require a sign-off","description":"Push a document to a role, crew, or person so they must read or sign it, and see who has and who hasn't completed it yet.","roles":["manager","supervisor"]}] as const;

/** Per-role grants within the documents module. */
export const DOCUMENTS_MATRIX: Record<EqRole, readonly DocumentsPermKey[]> = {
  "manager": [
    "documents.view",
    "documents.manage",
    "documents.assign"
  ],
  "supervisor": [
    "documents.view",
    "documents.manage",
    "documents.assign"
  ],
  "employee": [
    "documents.view"
  ],
  "apprentice": [
    "documents.view"
  ],
  "labour_hire": [
    "documents.view"
  ],
  "subcontractor": [
    "documents.view"
  ]
};

const _DOCUMENTS_SETS: Record<EqRole, Set<DocumentsPermKey>> = Object.fromEntries(
  (Object.keys(DOCUMENTS_MATRIX) as EqRole[]).map((r) => [r, new Set(DOCUMENTS_MATRIX[r])]),
) as Record<EqRole, Set<DocumentsPermKey>>;

export function documentsCan(role: EqRole, perm: DocumentsPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _DOCUMENTS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForDocuments(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly DocumentsPermKey[] {
  if (opts?.isPlatformAdmin) return DOCUMENTS_PERM_KEYS.slice();
  return DOCUMENTS_MATRIX[role] ?? [];
}

export function documentsCanAny(role: EqRole, perms: readonly DocumentsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _DOCUMENTS_SETS[role]?.has(p));
}

export function documentsCanAll(role: EqRole, perms: readonly DocumentsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _DOCUMENTS_SETS[role]?.has(p));
}
