/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/documents v2.7.2 — documents-module permission slice (runtime ESM). */

export const DOCUMENTS_PERM_KEYS = ['documents.view', 'documents.manage', 'documents.assign'];
export const DOCUMENTS_PERMISSIONS = [{"key":"documents.view","module":"documents","label":"View documents","description":"See the document library, and the documents assigned to you to read or sign.","roles":["manager","supervisor","employee","apprentice","labour_hire","subcontractor"]},{"key":"documents.manage","module":"documents","label":"Manage documents","description":"Upload document versions, archive documents, and add, rename, or delete categories.","roles":["manager","supervisor"]},{"key":"documents.assign","module":"documents","label":"Require a sign-off","description":"Push a document to a role, crew, or person so they must read or sign it, and see who has and who hasn't completed it yet.","roles":["manager","supervisor"]}];

/** Per-role grants within the documents module. */
export const DOCUMENTS_MATRIX = {
  "manager": [
    "documents.view",
    "documents.manage",
    "documents.assign"
  ],
  "supervisor": [
    "documents.view",
    "documents.manage",
    "documents.assign"
  ],
  "employee": [
    "documents.view"
  ],
  "apprentice": [
    "documents.view"
  ],
  "labour_hire": [
    "documents.view"
  ],
  "subcontractor": [
    "documents.view"
  ]
};

const _DOCUMENTS_SETS = Object.fromEntries(
  Object.keys(DOCUMENTS_MATRIX).map((r) => [r, new Set(DOCUMENTS_MATRIX[r])]),
);

export function documentsCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _DOCUMENTS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForDocuments(role, opts) {
  if (opts?.isPlatformAdmin) return DOCUMENTS_PERM_KEYS.slice();
  return DOCUMENTS_MATRIX[role] ?? [];
}

export function documentsCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _DOCUMENTS_SETS[role]?.has(p));
}

export function documentsCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _DOCUMENTS_SETS[role]?.has(p));
}
