/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/entity v2.7.1 — entity-module permission slice.
 * Import from "@eq-solutions/roles/entity" for typed entity.* perms only.
 * Full 60-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type EntityPermKey = 'entity.view' | 'entity.view_pii' | 'entity.create' | 'entity.edit' | 'entity.delete' | 'entity.manage_activation';
export const ENTITY_PERM_KEYS: readonly EntityPermKey[] = ['entity.view', 'entity.view_pii', 'entity.create', 'entity.edit', 'entity.delete', 'entity.manage_activation'];
export const ENTITY_PERMISSIONS = [{"key":"entity.view","module":"entity","label":"View records","description":"See customers, sites, contacts, and assets. Personal contact details are controlled separately.","roles":["manager","supervisor","employee","apprentice"]},{"key":"entity.view_pii","module":"entity","label":"See personal details","description":"See someone’s phone number, date of birth, and emergency contact. Kept separate from viewing records so people can look up a customer or site without seeing personal information.","roles":["manager","supervisor"]},{"key":"entity.create","module":"entity","label":"Add records","description":"Add a new customer, site, contact, or asset.","roles":["manager"]},{"key":"entity.edit","module":"entity","label":"Edit records","description":"Change the details on an existing customer, site, contact, or asset.","roles":["manager","supervisor"]},{"key":"entity.delete","module":"entity","label":"Delete records","description":"Permanently remove a customer, site, contact, or asset. This cannot be undone.","roles":["manager"]},{"key":"entity.manage_activation","module":"entity","label":"Show records in Field & Service","description":"Choose whether a site or customer appears in EQ Field and EQ Service.","roles":["manager"]}] as const;

/** Per-role grants within the entity module. */
export const ENTITY_MATRIX: Record<EqRole, readonly EntityPermKey[]> = {
  "manager": [
    "entity.view",
    "entity.view_pii",
    "entity.create",
    "entity.edit",
    "entity.delete",
    "entity.manage_activation"
  ],
  "supervisor": [
    "entity.view",
    "entity.view_pii",
    "entity.edit"
  ],
  "employee": [
    "entity.view"
  ],
  "apprentice": [
    "entity.view"
  ],
  "labour_hire": [],
  "subcontractor": []
};

const _ENTITY_SETS: Record<EqRole, Set<EntityPermKey>> = Object.fromEntries(
  (Object.keys(ENTITY_MATRIX) as EqRole[]).map((r) => [r, new Set(ENTITY_MATRIX[r])]),
) as Record<EqRole, Set<EntityPermKey>>;

export function entityCan(role: EqRole, perm: EntityPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _ENTITY_SETS[role]?.has(perm) ?? false;
}

export function permissionsForEntity(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly EntityPermKey[] {
  if (opts?.isPlatformAdmin) return ENTITY_PERM_KEYS.slice();
  return ENTITY_MATRIX[role] ?? [];
}

export function entityCanAny(role: EqRole, perms: readonly EntityPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _ENTITY_SETS[role]?.has(p));
}

export function entityCanAll(role: EqRole, perms: readonly EntityPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _ENTITY_SETS[role]?.has(p));
}
