/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/entity v2.1.0 — entity-module permission slice (runtime ESM). */

export const ENTITY_PERM_KEYS = ['entity.view', 'entity.create', 'entity.edit', 'entity.delete'];
export const ENTITY_PERMISSIONS = [{"key":"entity.view","module":"entity","description":"View canonical records (customers, sites, contacts, assets).","roles":["manager","supervisor","employee","apprentice"]},{"key":"entity.create","module":"entity","description":"Create a new canonical record.","roles":["manager"]},{"key":"entity.edit","module":"entity","description":"Edit an existing canonical record.","roles":["manager","supervisor"]},{"key":"entity.delete","module":"entity","description":"Delete a canonical record (hard delete, manager-only).","roles":["manager"]}];

/** Per-role grants within the entity module. */
export const ENTITY_MATRIX = {
  "manager": [
    "entity.view",
    "entity.create",
    "entity.edit",
    "entity.delete"
  ],
  "supervisor": [
    "entity.view",
    "entity.edit"
  ],
  "employee": [
    "entity.view"
  ],
  "apprentice": [
    "entity.view"
  ],
  "labour_hire": []
};

const _ENTITY_SETS = Object.fromEntries(
  Object.keys(ENTITY_MATRIX).map((r) => [r, new Set(ENTITY_MATRIX[r])]),
);

export function entityCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _ENTITY_SETS[role]?.has(perm) ?? false;
}

export function permissionsForEntity(role, opts) {
  if (opts?.isPlatformAdmin) return ENTITY_PERM_KEYS.slice();
  return ENTITY_MATRIX[role] ?? [];
}

export function entityCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _ENTITY_SETS[role]?.has(p));
}

export function entityCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _ENTITY_SETS[role]?.has(p));
}
