/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/entity v2.1.0 — entity-module permission slice.
 * Import from "@eq-solutions/roles/entity" for typed entity.* perms only.
 * Full 30-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire';

export type EntityPermKey = 'entity.view' | 'entity.create' | 'entity.edit' | 'entity.delete';
export const ENTITY_PERM_KEYS: readonly EntityPermKey[] = ['entity.view', 'entity.create', 'entity.edit', 'entity.delete'];
export const ENTITY_PERMISSIONS = [{"key":"entity.view","module":"entity","description":"View canonical records (customers, sites, contacts, assets).","roles":["manager","supervisor","employee","apprentice"]},{"key":"entity.create","module":"entity","description":"Create a new canonical record.","roles":["manager"]},{"key":"entity.edit","module":"entity","description":"Edit an existing canonical record.","roles":["manager","supervisor"]},{"key":"entity.delete","module":"entity","description":"Delete a canonical record (hard delete, manager-only).","roles":["manager"]}] as const;

/** Per-role grants within the entity module. */
export const ENTITY_MATRIX: Record<EqRole, readonly EntityPermKey[]> = {
  "manager": [
    "entity.view",
    "entity.create",
    "entity.edit",
    "entity.delete"
  ],
  "supervisor": [
    "entity.view",
    "entity.edit"
  ],
  "employee": [
    "entity.view"
  ],
  "apprentice": [
    "entity.view"
  ],
  "labour_hire": []
};

const _ENTITY_SETS: Record<EqRole, Set<EntityPermKey>> = Object.fromEntries(
  (Object.keys(ENTITY_MATRIX) as EqRole[]).map((r) => [r, new Set(ENTITY_MATRIX[r])]),
) as Record<EqRole, Set<EntityPermKey>>;

export function entityCan(role: EqRole, perm: EntityPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _ENTITY_SETS[role]?.has(perm) ?? false;
}

export function permissionsForEntity(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly EntityPermKey[] {
  if (opts?.isPlatformAdmin) return ENTITY_PERM_KEYS.slice();
  return ENTITY_MATRIX[role] ?? [];
}

export function entityCanAny(role: EqRole, perms: readonly EntityPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _ENTITY_SETS[role]?.has(p));
}

export function entityCanAll(role: EqRole, perms: readonly EntityPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _ENTITY_SETS[role]?.has(p));
}
