/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/equipment v2.0.0 — equipment-module permission slice.
 * Import from "@eq-solutions/roles/equipment" for typed equipment.* perms only.
 * Full 30-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire';

export type EquipmentPermKey = 'equipment.view' | 'equipment.edit';
export const EQUIPMENT_PERM_KEYS: readonly EquipmentPermKey[] = ['equipment.view', 'equipment.edit'];
export const EQUIPMENT_PERMISSIONS = [{"key":"equipment.view","module":"equipment","description":"See the Plant & Equipment list + calibration.","roles":["manager","supervisor","employee"]},{"key":"equipment.edit","module":"equipment","description":"Add / edit equipment + calibration fields.","roles":["manager","supervisor"]}] as const;

/** Per-role grants within the equipment module. */
export const EQUIPMENT_MATRIX: Record<EqRole, readonly EquipmentPermKey[]> = {
  "manager": [
    "equipment.view",
    "equipment.edit"
  ],
  "supervisor": [
    "equipment.view",
    "equipment.edit"
  ],
  "employee": [
    "equipment.view"
  ],
  "apprentice": [],
  "labour_hire": []
};

const _EQUIPMENT_SETS: Record<EqRole, Set<EquipmentPermKey>> = Object.fromEntries(
  (Object.keys(EQUIPMENT_MATRIX) as EqRole[]).map((r) => [r, new Set(EQUIPMENT_MATRIX[r])]),
) as Record<EqRole, Set<EquipmentPermKey>>;

export function equipmentCan(role: EqRole, perm: EquipmentPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _EQUIPMENT_SETS[role]?.has(perm) ?? false;
}

export function permissionsForEquipment(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly EquipmentPermKey[] {
  if (opts?.isPlatformAdmin) return EQUIPMENT_PERM_KEYS.slice();
  return EQUIPMENT_MATRIX[role] ?? [];
}

export function equipmentCanAny(role: EqRole, perms: readonly EquipmentPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _EQUIPMENT_SETS[role]?.has(p));
}

export function equipmentCanAll(role: EqRole, perms: readonly EquipmentPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _EQUIPMENT_SETS[role]?.has(p));
}
