/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/equipment v2.7.4 — equipment-module permission slice (runtime ESM). */

export const EQUIPMENT_PERM_KEYS = ['equipment.view', 'equipment.edit'];
export const EQUIPMENT_PERMISSIONS = [{"key":"equipment.view","module":"equipment","label":"View equipment","description":"See the plant and equipment list, including calibration dates.","roles":["manager","supervisor","employee","apprentice","labour_hire"]},{"key":"equipment.edit","module":"equipment","label":"Edit equipment","description":"Add equipment, change its details, or update calibration dates.","roles":["manager","supervisor"]}];

/** Per-role grants within the equipment module. */
export const EQUIPMENT_MATRIX = {
  "manager": [
    "equipment.view",
    "equipment.edit"
  ],
  "supervisor": [
    "equipment.view",
    "equipment.edit"
  ],
  "employee": [
    "equipment.view"
  ],
  "apprentice": [
    "equipment.view"
  ],
  "labour_hire": [
    "equipment.view"
  ],
  "subcontractor": []
};

const _EQUIPMENT_SETS = Object.fromEntries(
  Object.keys(EQUIPMENT_MATRIX).map((r) => [r, new Set(EQUIPMENT_MATRIX[r])]),
);

export function equipmentCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _EQUIPMENT_SETS[role]?.has(perm) ?? false;
}

export function permissionsForEquipment(role, opts) {
  if (opts?.isPlatformAdmin) return EQUIPMENT_PERM_KEYS.slice();
  return EQUIPMENT_MATRIX[role] ?? [];
}

export function equipmentCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _EQUIPMENT_SETS[role]?.has(p));
}

export function equipmentCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _EQUIPMENT_SETS[role]?.has(p));
}
