/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/field v2.5.3 — field-module permission slice (runtime ESM). */

export const FIELD_PERM_KEYS = ['field.view', 'field.view_hours', 'field.view_licences', 'field.view_rates', 'field.dispatch', 'field.manage_roster', 'field.manage_licences', 'field.manage_labour_hire'];
export const FIELD_PERMISSIONS = [{"key":"field.view","module":"field","label":"View field resources","description":"View Field resources — staff, licences, availability, assignments.","roles":["manager","supervisor","employee","apprentice","labour_hire","subcontractor"]},{"key":"field.view_hours","module":"field","label":"See timesheets & hours","description":"See worker timesheets / hours (pay-adjacent). Split out of field.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"field.view_licences","module":"field","label":"See worker licences","description":"See worker licences & compliance status. Split out of field.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"field.view_rates","module":"field","label":"See charge rates","description":"See labour-hire / charge rates (commercial). Split out of field.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"field.dispatch","module":"field","label":"Dispatch staff","description":"Dispatch staff to jobs / shifts.","roles":["manager","supervisor"]},{"key":"field.manage_roster","module":"field","label":"Build & edit the roster","description":"Build and edit the crew roster. A distinct owner from day-to-day dispatch (2026-07-17 access-model cluster 3).","roles":["manager","supervisor"]},{"key":"field.manage_licences","module":"field","label":"Manage worker licences","description":"Add / verify worker licences and compliance records. Sign-off action, matches field.view_licences' tier (2026-07-17 access-model cluster 3).","roles":["manager","supervisor"]},{"key":"field.manage_labour_hire","module":"field","label":"Manage labour-hire companies","description":"Manage labour-hire companies & their charge rates. Commercially sensitive, matches ops.manage_rates' tier (2026-07-17 access-model cluster 3).","roles":["manager","supervisor"]}];

/** Per-role grants within the field module. */
export const FIELD_MATRIX = {
  "manager": [
    "field.view",
    "field.view_hours",
    "field.view_licences",
    "field.view_rates",
    "field.dispatch",
    "field.manage_roster",
    "field.manage_licences",
    "field.manage_labour_hire"
  ],
  "supervisor": [
    "field.view",
    "field.view_hours",
    "field.view_licences",
    "field.view_rates",
    "field.dispatch",
    "field.manage_roster",
    "field.manage_licences",
    "field.manage_labour_hire"
  ],
  "employee": [
    "field.view"
  ],
  "apprentice": [
    "field.view"
  ],
  "labour_hire": [
    "field.view"
  ],
  "subcontractor": [
    "field.view"
  ]
};

const _FIELD_SETS = Object.fromEntries(
  Object.keys(FIELD_MATRIX).map((r) => [r, new Set(FIELD_MATRIX[r])]),
);

export function fieldCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _FIELD_SETS[role]?.has(perm) ?? false;
}

export function permissionsForField(role, opts) {
  if (opts?.isPlatformAdmin) return FIELD_PERM_KEYS.slice();
  return FIELD_MATRIX[role] ?? [];
}

export function fieldCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _FIELD_SETS[role]?.has(p));
}

export function fieldCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _FIELD_SETS[role]?.has(p));
}
