/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/field v2.5.2 — field-module permission slice.
 * Import from "@eq-solutions/roles/field" for typed field.* perms only.
 * Full 40-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type FieldPermKey = 'field.view' | 'field.view_hours' | 'field.view_licences' | 'field.view_rates' | 'field.dispatch';
export const FIELD_PERM_KEYS: readonly FieldPermKey[] = ['field.view', 'field.view_hours', 'field.view_licences', 'field.view_rates', 'field.dispatch'];
export const FIELD_PERMISSIONS = [{"key":"field.view","module":"field","label":"View field resources","description":"View Field resources — staff, licences, availability, assignments.","roles":["manager","supervisor","employee","apprentice","labour_hire","subcontractor"]},{"key":"field.view_hours","module":"field","label":"See timesheets & hours","description":"See worker timesheets / hours (pay-adjacent). Split out of field.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"field.view_licences","module":"field","label":"See worker licences","description":"See worker licences & compliance status. Split out of field.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"field.view_rates","module":"field","label":"See charge rates","description":"See labour-hire / charge rates (commercial). Split out of field.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"field.dispatch","module":"field","label":"Dispatch staff","description":"Dispatch staff to jobs / shifts.","roles":["manager","supervisor"]}] as const;

/** Per-role grants within the field module. */
export const FIELD_MATRIX: Record<EqRole, readonly FieldPermKey[]> = {
  "manager": [
    "field.view",
    "field.view_hours",
    "field.view_licences",
    "field.view_rates",
    "field.dispatch"
  ],
  "supervisor": [
    "field.view",
    "field.view_hours",
    "field.view_licences",
    "field.view_rates",
    "field.dispatch"
  ],
  "employee": [
    "field.view"
  ],
  "apprentice": [
    "field.view"
  ],
  "labour_hire": [
    "field.view"
  ],
  "subcontractor": [
    "field.view"
  ]
};

const _FIELD_SETS: Record<EqRole, Set<FieldPermKey>> = Object.fromEntries(
  (Object.keys(FIELD_MATRIX) as EqRole[]).map((r) => [r, new Set(FIELD_MATRIX[r])]),
) as Record<EqRole, Set<FieldPermKey>>;

export function fieldCan(role: EqRole, perm: FieldPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _FIELD_SETS[role]?.has(perm) ?? false;
}

export function permissionsForField(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly FieldPermKey[] {
  if (opts?.isPlatformAdmin) return FIELD_PERM_KEYS.slice();
  return FIELD_MATRIX[role] ?? [];
}

export function fieldCanAny(role: EqRole, perms: readonly FieldPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _FIELD_SETS[role]?.has(p));
}

export function fieldCanAll(role: EqRole, perms: readonly FieldPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _FIELD_SETS[role]?.has(p));
}
