/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/field v2.5.0 — field-module permission slice (runtime ESM). */

export const FIELD_PERM_KEYS = ['field.view', 'field.dispatch'];
export const FIELD_PERMISSIONS = [{"key":"field.view","module":"field","label":"View field resources","description":"View Field resources — staff, licences, availability, assignments.","roles":["manager","supervisor","employee","apprentice","labour_hire","subcontractor"]},{"key":"field.dispatch","module":"field","label":"Dispatch staff","description":"Dispatch staff to jobs / shifts.","roles":["manager","supervisor"]}];

/** Per-role grants within the field module. */
export const FIELD_MATRIX = {
  "manager": [
    "field.view",
    "field.dispatch"
  ],
  "supervisor": [
    "field.view",
    "field.dispatch"
  ],
  "employee": [
    "field.view"
  ],
  "apprentice": [
    "field.view"
  ],
  "labour_hire": [
    "field.view"
  ],
  "subcontractor": [
    "field.view"
  ]
};

const _FIELD_SETS = Object.fromEntries(
  Object.keys(FIELD_MATRIX).map((r) => [r, new Set(FIELD_MATRIX[r])]),
);

export function fieldCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _FIELD_SETS[role]?.has(perm) ?? false;
}

export function permissionsForField(role, opts) {
  if (opts?.isPlatformAdmin) return FIELD_PERM_KEYS.slice();
  return FIELD_MATRIX[role] ?? [];
}

export function fieldCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _FIELD_SETS[role]?.has(p));
}

export function fieldCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _FIELD_SETS[role]?.has(p));
}
