/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/intake v2.2.0 — intake-module permission slice.
 * Import from "@eq-solutions/roles/intake" for typed intake.* perms only.
 * Full 30-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire';

export type IntakePermKey = 'intake.view' | 'intake.import' | 'intake.commit';
export const INTAKE_PERM_KEYS: readonly IntakePermKey[] = ['intake.view', 'intake.import', 'intake.commit'];
export const INTAKE_PERMISSIONS = [{"key":"intake.view","module":"intake","label":"View imports","description":"See the Intake surface.","roles":["manager","supervisor","employee","apprentice"]},{"key":"intake.import","module":"intake","label":"Start an import","description":"Initiate an import (drop file, map, validate).","roles":["manager","supervisor","employee"]},{"key":"intake.commit","module":"intake","label":"Confirm an import","description":"Commit a validated batch to canonical (destructive).","roles":["manager","supervisor"]}] as const;

/** Per-role grants within the intake module. */
export const INTAKE_MATRIX: Record<EqRole, readonly IntakePermKey[]> = {
  "manager": [
    "intake.view",
    "intake.import",
    "intake.commit"
  ],
  "supervisor": [
    "intake.view",
    "intake.import",
    "intake.commit"
  ],
  "employee": [
    "intake.view",
    "intake.import"
  ],
  "apprentice": [
    "intake.view"
  ],
  "labour_hire": []
};

const _INTAKE_SETS: Record<EqRole, Set<IntakePermKey>> = Object.fromEntries(
  (Object.keys(INTAKE_MATRIX) as EqRole[]).map((r) => [r, new Set(INTAKE_MATRIX[r])]),
) as Record<EqRole, Set<IntakePermKey>>;

export function intakeCan(role: EqRole, perm: IntakePermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _INTAKE_SETS[role]?.has(perm) ?? false;
}

export function permissionsForIntake(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly IntakePermKey[] {
  if (opts?.isPlatformAdmin) return INTAKE_PERM_KEYS.slice();
  return INTAKE_MATRIX[role] ?? [];
}

export function intakeCanAny(role: EqRole, perms: readonly IntakePermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _INTAKE_SETS[role]?.has(p));
}

export function intakeCanAll(role: EqRole, perms: readonly IntakePermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _INTAKE_SETS[role]?.has(p));
}
