/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/intake v2.5.3 — intake-module permission slice (runtime ESM). */

export const INTAKE_PERM_KEYS = ['intake.view', 'intake.import', 'intake.commit'];
export const INTAKE_PERMISSIONS = [{"key":"intake.view","module":"intake","label":"View imports","description":"See the Intake surface.","roles":["manager","supervisor","employee","apprentice"]},{"key":"intake.import","module":"intake","label":"Start an import","description":"Initiate an import (drop file, map, validate).","roles":["manager","supervisor","employee"]},{"key":"intake.commit","module":"intake","label":"Confirm an import","description":"Commit a validated batch to canonical (destructive).","roles":["manager","supervisor"]}];

/** Per-role grants within the intake module. */
export const INTAKE_MATRIX = {
  "manager": [
    "intake.view",
    "intake.import",
    "intake.commit"
  ],
  "supervisor": [
    "intake.view",
    "intake.import",
    "intake.commit"
  ],
  "employee": [
    "intake.view",
    "intake.import"
  ],
  "apprentice": [
    "intake.view"
  ],
  "labour_hire": [],
  "subcontractor": []
};

const _INTAKE_SETS = Object.fromEntries(
  Object.keys(INTAKE_MATRIX).map((r) => [r, new Set(INTAKE_MATRIX[r])]),
);

export function intakeCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _INTAKE_SETS[role]?.has(perm) ?? false;
}

export function permissionsForIntake(role, opts) {
  if (opts?.isPlatformAdmin) return INTAKE_PERM_KEYS.slice();
  return INTAKE_MATRIX[role] ?? [];
}

export function intakeCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _INTAKE_SETS[role]?.has(p));
}

export function intakeCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _INTAKE_SETS[role]?.has(p));
}
