/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/ops v2.5.3 — ops-module permission slice.
 * Import from "@eq-solutions/roles/ops" for typed ops.* perms only.
 * Full 46-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type OpsPermKey = 'ops.view_rates' | 'ops.view_margins' | 'ops.manage_rates' | 'ops.create_job';
export const OPS_PERM_KEYS: readonly OpsPermKey[] = ['ops.view_rates', 'ops.view_margins', 'ops.manage_rates', 'ops.create_job'];
export const OPS_PERMISSIONS = [{"key":"ops.view_rates","module":"ops","label":"View labour hire rates","description":"View labour hire cost rate cards. Commercially sensitive — manager + supervisor (project management) only.","roles":["manager","supervisor"]},{"key":"ops.view_margins","module":"ops","label":"See cost & margin","description":"See cost and margin on a quote / job. Split out of quotes.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"ops.manage_rates","module":"ops","label":"Manage labour hire rates","description":"Import, edit, or manually adjust labour hire cost rate cards.","roles":["manager","supervisor"]},{"key":"ops.create_job","module":"ops","label":"Convert quote to a job","description":"Convert an approved quote into a numbered job. A commitment gate, matches quotes.create's tier (job numbers are manual/Smartsheet, never auto-generated) (2026-07-17 access-model cluster 3).","roles":["manager","supervisor"]}] as const;

/** Per-role grants within the ops module. */
export const OPS_MATRIX: Record<EqRole, readonly OpsPermKey[]> = {
  "manager": [
    "ops.view_rates",
    "ops.view_margins",
    "ops.manage_rates",
    "ops.create_job"
  ],
  "supervisor": [
    "ops.view_rates",
    "ops.view_margins",
    "ops.manage_rates",
    "ops.create_job"
  ],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _OPS_SETS: Record<EqRole, Set<OpsPermKey>> = Object.fromEntries(
  (Object.keys(OPS_MATRIX) as EqRole[]).map((r) => [r, new Set(OPS_MATRIX[r])]),
) as Record<EqRole, Set<OpsPermKey>>;

export function opsCan(role: EqRole, perm: OpsPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _OPS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForOps(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly OpsPermKey[] {
  if (opts?.isPlatformAdmin) return OPS_PERM_KEYS.slice();
  return OPS_MATRIX[role] ?? [];
}

export function opsCanAny(role: EqRole, perms: readonly OpsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _OPS_SETS[role]?.has(p));
}

export function opsCanAll(role: EqRole, perms: readonly OpsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _OPS_SETS[role]?.has(p));
}
