/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/ops v2.5.4 — ops-module permission slice (runtime ESM). */

export const OPS_PERM_KEYS = ['ops.view_rates', 'ops.view_margins', 'ops.manage_rates', 'ops.create_job', 'ops.view_suppliers', 'ops.manage_suppliers'];
export const OPS_PERMISSIONS = [{"key":"ops.view_rates","module":"ops","label":"View labour hire rates","description":"View labour hire cost rate cards. Commercially sensitive — manager + supervisor (project management) only.","roles":["manager","supervisor"]},{"key":"ops.view_margins","module":"ops","label":"See cost & margin","description":"See cost and margin on a quote / job. Split out of quotes.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"ops.manage_rates","module":"ops","label":"Manage labour hire rates","description":"Import, edit, or manually adjust labour hire cost rate cards.","roles":["manager","supervisor"]},{"key":"ops.create_job","module":"ops","label":"Convert quote to a job","description":"Convert an approved quote into a numbered job. A commitment gate, matches quotes.create's tier (job numbers are manual/Smartsheet, never auto-generated) (2026-07-17 access-model cluster 3).","roles":["manager","supervisor"]},{"key":"ops.view_suppliers","module":"ops","label":"View suppliers directory","description":"View the trade suppliers/wholesalers/hire companies directory. Matches ops.view_rates' tier (2026-07-26 access-model Phase 3). Promotes a key eq-shell's own client matrix already declared but the package didn't yet have — see suppliers-mutate.ts.","roles":["manager","supervisor"]},{"key":"ops.manage_suppliers","module":"ops","label":"Manage suppliers directory","description":"Add / edit / delete suppliers directory entries. Was reusing ops.manage_rates as an interim server-side gate until this key existed in the package (2026-07-26 access-model Phase 3).","roles":["manager","supervisor"]}];

/** Per-role grants within the ops module. */
export const OPS_MATRIX = {
  "manager": [
    "ops.view_rates",
    "ops.view_margins",
    "ops.manage_rates",
    "ops.create_job",
    "ops.view_suppliers",
    "ops.manage_suppliers"
  ],
  "supervisor": [
    "ops.view_rates",
    "ops.view_margins",
    "ops.manage_rates",
    "ops.create_job",
    "ops.view_suppliers",
    "ops.manage_suppliers"
  ],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _OPS_SETS = Object.fromEntries(
  Object.keys(OPS_MATRIX).map((r) => [r, new Set(OPS_MATRIX[r])]),
);

export function opsCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _OPS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForOps(role, opts) {
  if (opts?.isPlatformAdmin) return OPS_PERM_KEYS.slice();
  return OPS_MATRIX[role] ?? [];
}

export function opsCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _OPS_SETS[role]?.has(p));
}

export function opsCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _OPS_SETS[role]?.has(p));
}
