/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/ops v2.7.4 — ops-module permission slice.
 * Import from "@eq-solutions/roles/ops" for typed ops.* perms only.
 * Full 61-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type OpsPermKey = 'ops.view_rates' | 'ops.view_margins' | 'ops.manage_rates' | 'ops.create_job' | 'ops.view_suppliers' | 'ops.manage_suppliers' | 'ops.view_supplier_credentials';
export const OPS_PERM_KEYS: readonly OpsPermKey[] = ['ops.view_rates', 'ops.view_margins', 'ops.manage_rates', 'ops.create_job', 'ops.view_suppliers', 'ops.manage_suppliers', 'ops.view_supplier_credentials'];
export const OPS_PERMISSIONS = [{"key":"ops.view_rates","module":"ops","label":"View rates & pricing setup","description":"See what labour-hire agencies charge, and open Setup — where pricing, the rate library, quote templates, and estimators are configured.","roles":["manager","supervisor"]},{"key":"ops.view_margins","module":"ops","label":"See cost & margin","description":"See what a job costs and what you make on it. Kept separate from viewing quotes so people can work on a quote without seeing the margin.","roles":["manager","supervisor"]},{"key":"ops.manage_rates","module":"ops","label":"Manage rates & pricing setup","description":"Add, import, or change labour-hire rate cards and the pricing setup.","roles":["manager","supervisor"]},{"key":"ops.create_job","module":"ops","label":"Convert quote to a job","description":"Turn an accepted quote into a numbered job. Job numbers are entered by hand, so this is a deliberate commitment step.","roles":["manager","supervisor"]},{"key":"ops.view_suppliers","module":"ops","label":"View suppliers directory","description":"See the list of trade suppliers, wholesalers, and hire companies.","roles":["manager","supervisor"]},{"key":"ops.manage_suppliers","module":"ops","label":"Manage suppliers directory","description":"Add, change, or remove entries in the suppliers list.","roles":["manager","supervisor"]},{"key":"ops.view_supplier_credentials","module":"ops","label":"See supplier login/password","description":"See the account login and password saved against a supplier. Kept separate so people can use the supplier list without seeing stored passwords.","roles":["manager","supervisor"]}] as const;

/** Per-role grants within the ops module. */
export const OPS_MATRIX: Record<EqRole, readonly OpsPermKey[]> = {
  "manager": [
    "ops.view_rates",
    "ops.view_margins",
    "ops.manage_rates",
    "ops.create_job",
    "ops.view_suppliers",
    "ops.manage_suppliers",
    "ops.view_supplier_credentials"
  ],
  "supervisor": [
    "ops.view_rates",
    "ops.view_margins",
    "ops.manage_rates",
    "ops.create_job",
    "ops.view_suppliers",
    "ops.manage_suppliers",
    "ops.view_supplier_credentials"
  ],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _OPS_SETS: Record<EqRole, Set<OpsPermKey>> = Object.fromEntries(
  (Object.keys(OPS_MATRIX) as EqRole[]).map((r) => [r, new Set(OPS_MATRIX[r])]),
) as Record<EqRole, Set<OpsPermKey>>;

export function opsCan(role: EqRole, perm: OpsPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _OPS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForOps(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly OpsPermKey[] {
  if (opts?.isPlatformAdmin) return OPS_PERM_KEYS.slice();
  return OPS_MATRIX[role] ?? [];
}

export function opsCanAny(role: EqRole, perms: readonly OpsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _OPS_SETS[role]?.has(p));
}

export function opsCanAll(role: EqRole, perms: readonly OpsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _OPS_SETS[role]?.has(p));
}
