/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/ops v2.5.2 — ops-module permission slice (runtime ESM). */

export const OPS_PERM_KEYS = ['ops.view_rates', 'ops.view_margins', 'ops.manage_rates'];
export const OPS_PERMISSIONS = [{"key":"ops.view_rates","module":"ops","label":"View labour hire rates","description":"View labour hire cost rate cards. Commercially sensitive — manager + supervisor (project management) only.","roles":["manager","supervisor"]},{"key":"ops.view_margins","module":"ops","label":"See cost & margin","description":"See cost and margin on a quote / job. Split out of quotes.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"ops.manage_rates","module":"ops","label":"Manage labour hire rates","description":"Import, edit, or manually adjust labour hire cost rate cards.","roles":["manager","supervisor"]}];

/** Per-role grants within the ops module. */
export const OPS_MATRIX = {
  "manager": [
    "ops.view_rates",
    "ops.view_margins",
    "ops.manage_rates"
  ],
  "supervisor": [
    "ops.view_rates",
    "ops.view_margins",
    "ops.manage_rates"
  ],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _OPS_SETS = Object.fromEntries(
  Object.keys(OPS_MATRIX).map((r) => [r, new Set(OPS_MATRIX[r])]),
);

export function opsCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _OPS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForOps(role, opts) {
  if (opts?.isPlatformAdmin) return OPS_PERM_KEYS.slice();
  return OPS_MATRIX[role] ?? [];
}

export function opsCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _OPS_SETS[role]?.has(p));
}

export function opsCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _OPS_SETS[role]?.has(p));
}
