/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/quotes v2.5.0 — quotes-module permission slice.
 * Import from "@eq-solutions/roles/quotes" for typed quotes.* perms only.
 * Full 30-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type QuotesPermKey = 'quotes.view' | 'quotes.create' | 'quotes.approve';
export const QUOTES_PERM_KEYS: readonly QuotesPermKey[] = ['quotes.view', 'quotes.create', 'quotes.approve'];
export const QUOTES_PERMISSIONS = [{"key":"quotes.view","module":"quotes","label":"View quotes","description":"View quotes.","roles":["manager","supervisor","employee"]},{"key":"quotes.create","module":"quotes","label":"Create quotes","description":"Create or edit a quote.","roles":["manager","supervisor"]},{"key":"quotes.approve","module":"quotes","label":"Approve quotes","description":"Approve and send a quote.","roles":["manager"]}] as const;

/** Per-role grants within the quotes module. */
export const QUOTES_MATRIX: Record<EqRole, readonly QuotesPermKey[]> = {
  "manager": [
    "quotes.view",
    "quotes.create",
    "quotes.approve"
  ],
  "supervisor": [
    "quotes.view",
    "quotes.create"
  ],
  "employee": [
    "quotes.view"
  ],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _QUOTES_SETS: Record<EqRole, Set<QuotesPermKey>> = Object.fromEntries(
  (Object.keys(QUOTES_MATRIX) as EqRole[]).map((r) => [r, new Set(QUOTES_MATRIX[r])]),
) as Record<EqRole, Set<QuotesPermKey>>;

export function quotesCan(role: EqRole, perm: QuotesPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _QUOTES_SETS[role]?.has(perm) ?? false;
}

export function permissionsForQuotes(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly QuotesPermKey[] {
  if (opts?.isPlatformAdmin) return QUOTES_PERM_KEYS.slice();
  return QUOTES_MATRIX[role] ?? [];
}

export function quotesCanAny(role: EqRole, perms: readonly QuotesPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _QUOTES_SETS[role]?.has(p));
}

export function quotesCanAll(role: EqRole, perms: readonly QuotesPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _QUOTES_SETS[role]?.has(p));
}
