/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/quotes v2.1.0 — quotes-module permission slice (runtime ESM). */

export const QUOTES_PERM_KEYS = ['quotes.view', 'quotes.create', 'quotes.approve'];
export const QUOTES_PERMISSIONS = [{"key":"quotes.view","module":"quotes","label":"View quotes","description":"View quotes.","roles":["manager","supervisor","employee"]},{"key":"quotes.create","module":"quotes","label":"Create quotes","description":"Create or edit a quote.","roles":["manager","supervisor"]},{"key":"quotes.approve","module":"quotes","label":"Approve quotes","description":"Approve and send a quote.","roles":["manager"]}];

/** Per-role grants within the quotes module. */
export const QUOTES_MATRIX = {
  "manager": [
    "quotes.view",
    "quotes.create",
    "quotes.approve"
  ],
  "supervisor": [
    "quotes.view",
    "quotes.create"
  ],
  "employee": [
    "quotes.view"
  ],
  "apprentice": [],
  "labour_hire": []
};

const _QUOTES_SETS = Object.fromEntries(
  Object.keys(QUOTES_MATRIX).map((r) => [r, new Set(QUOTES_MATRIX[r])]),
);

export function quotesCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _QUOTES_SETS[role]?.has(perm) ?? false;
}

export function permissionsForQuotes(role, opts) {
  if (opts?.isPlatformAdmin) return QUOTES_PERM_KEYS.slice();
  return QUOTES_MATRIX[role] ?? [];
}

export function quotesCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _QUOTES_SETS[role]?.has(p));
}

export function quotesCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _QUOTES_SETS[role]?.has(p));
}
