/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/reports v2.7.0 — reports-module permission slice.
 * Import from "@eq-solutions/roles/reports" for typed reports.* perms only.
 * Full 60-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type ReportsPermKey = 'reports.view' | 'reports.view_financial' | 'reports.upload' | 'reports.generate_briefing' | 'reports.manage';
export const REPORTS_PERM_KEYS: readonly ReportsPermKey[] = ['reports.view', 'reports.view_financial', 'reports.upload', 'reports.generate_briefing', 'reports.manage'];
export const REPORTS_PERMISSIONS = [{"key":"reports.view","module":"reports","label":"View reports","description":"Open the management reports.","roles":["manager"]},{"key":"reports.view_financial","module":"reports","label":"See financial reports","description":"See reports that include revenue, cost, and margin figures.","roles":["manager"],"deprecated":"Every report today includes financial figures, so this grants nothing that reports.view doesn't already. Kept only so nobody's existing access breaks; do not grant to anyone new. Bring this back if a non-financial report is ever added."},{"key":"reports.upload","module":"reports","label":"Upload reports","description":"Upload a source file that reports are built from.","roles":["manager"]},{"key":"reports.generate_briefing","module":"reports","label":"Generate AI briefing","description":"Produce the AI-written summary of recent activity.","roles":["manager"]},{"key":"reports.manage","module":"reports","label":"Archive or delete reports","description":"Archive a reporting period, or permanently delete one and its job rows. This cannot be undone.","roles":["manager"]}] as const;

/** Per-role grants within the reports module. */
export const REPORTS_MATRIX: Record<EqRole, readonly ReportsPermKey[]> = {
  "manager": [
    "reports.view",
    "reports.view_financial",
    "reports.upload",
    "reports.generate_briefing",
    "reports.manage"
  ],
  "supervisor": [],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _REPORTS_SETS: Record<EqRole, Set<ReportsPermKey>> = Object.fromEntries(
  (Object.keys(REPORTS_MATRIX) as EqRole[]).map((r) => [r, new Set(REPORTS_MATRIX[r])]),
) as Record<EqRole, Set<ReportsPermKey>>;

export function reportsCan(role: EqRole, perm: ReportsPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _REPORTS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForReports(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly ReportsPermKey[] {
  if (opts?.isPlatformAdmin) return REPORTS_PERM_KEYS.slice();
  return REPORTS_MATRIX[role] ?? [];
}

export function reportsCanAny(role: EqRole, perms: readonly ReportsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _REPORTS_SETS[role]?.has(p));
}

export function reportsCanAll(role: EqRole, perms: readonly ReportsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _REPORTS_SETS[role]?.has(p));
}
