/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/reports v2.5.0 — reports-module permission slice.
 * Import from "@eq-solutions/roles/reports" for typed reports.* perms only.
 * Full 30-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type ReportsPermKey = 'reports.view' | 'reports.upload' | 'reports.generate_briefing';
export const REPORTS_PERM_KEYS: readonly ReportsPermKey[] = ['reports.view', 'reports.upload', 'reports.generate_briefing'];
export const REPORTS_PERMISSIONS = [{"key":"reports.view","module":"reports","label":"View reports","description":"View GM reports.","roles":["manager"]},{"key":"reports.upload","module":"reports","label":"Upload reports","description":"Upload a source report.","roles":["manager"]},{"key":"reports.generate_briefing","module":"reports","label":"Generate AI briefing","description":"Generate the AI briefing.","roles":["manager"]}] as const;

/** Per-role grants within the reports module. */
export const REPORTS_MATRIX: Record<EqRole, readonly ReportsPermKey[]> = {
  "manager": [
    "reports.view",
    "reports.upload",
    "reports.generate_briefing"
  ],
  "supervisor": [],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _REPORTS_SETS: Record<EqRole, Set<ReportsPermKey>> = Object.fromEntries(
  (Object.keys(REPORTS_MATRIX) as EqRole[]).map((r) => [r, new Set(REPORTS_MATRIX[r])]),
) as Record<EqRole, Set<ReportsPermKey>>;

export function reportsCan(role: EqRole, perm: ReportsPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _REPORTS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForReports(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly ReportsPermKey[] {
  if (opts?.isPlatformAdmin) return REPORTS_PERM_KEYS.slice();
  return REPORTS_MATRIX[role] ?? [];
}

export function reportsCanAny(role: EqRole, perms: readonly ReportsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _REPORTS_SETS[role]?.has(p));
}

export function reportsCanAll(role: EqRole, perms: readonly ReportsPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _REPORTS_SETS[role]?.has(p));
}
