/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/reports v2.7.3 — reports-module permission slice (runtime ESM). */

export const REPORTS_PERM_KEYS = ['reports.view', 'reports.view_financial', 'reports.upload', 'reports.generate_briefing', 'reports.manage'];
export const REPORTS_PERMISSIONS = [{"key":"reports.view","module":"reports","label":"View reports","description":"Open the management reports.","roles":["manager"]},{"key":"reports.view_financial","module":"reports","label":"See financial reports","description":"See the cash, cost, and margin figures inside GM Reports. Kept separate from reports.view so a security group can grant someone reports without also handing them the money.","roles":["manager"]},{"key":"reports.upload","module":"reports","label":"Upload reports","description":"Upload a source file that reports are built from.","roles":["manager"]},{"key":"reports.generate_briefing","module":"reports","label":"Generate AI briefing","description":"Produce the AI-written summary of recent activity.","roles":["manager"]},{"key":"reports.manage","module":"reports","label":"Archive or delete reports","description":"Archive a reporting period, or permanently delete one and its job rows. This cannot be undone.","roles":["manager"]}];

/** Per-role grants within the reports module. */
export const REPORTS_MATRIX = {
  "manager": [
    "reports.view",
    "reports.view_financial",
    "reports.upload",
    "reports.generate_briefing",
    "reports.manage"
  ],
  "supervisor": [],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _REPORTS_SETS = Object.fromEntries(
  Object.keys(REPORTS_MATRIX).map((r) => [r, new Set(REPORTS_MATRIX[r])]),
);

export function reportsCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _REPORTS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForReports(role, opts) {
  if (opts?.isPlatformAdmin) return REPORTS_PERM_KEYS.slice();
  return REPORTS_MATRIX[role] ?? [];
}

export function reportsCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _REPORTS_SETS[role]?.has(p));
}

export function reportsCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _REPORTS_SETS[role]?.has(p));
}
