/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/reports v2.4.0 — reports-module permission slice (runtime ESM). */

export const REPORTS_PERM_KEYS = ['reports.view', 'reports.upload', 'reports.generate_briefing'];
export const REPORTS_PERMISSIONS = [{"key":"reports.view","module":"reports","label":"View reports","description":"View GM reports.","roles":["manager"]},{"key":"reports.upload","module":"reports","label":"Upload reports","description":"Upload a source report.","roles":["manager"]},{"key":"reports.generate_briefing","module":"reports","label":"Generate AI briefing","description":"Generate the AI briefing.","roles":["manager"]}];

/** Per-role grants within the reports module. */
export const REPORTS_MATRIX = {
  "manager": [
    "reports.view",
    "reports.upload",
    "reports.generate_briefing"
  ],
  "supervisor": [],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _REPORTS_SETS = Object.fromEntries(
  Object.keys(REPORTS_MATRIX).map((r) => [r, new Set(REPORTS_MATRIX[r])]),
);

export function reportsCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _REPORTS_SETS[role]?.has(perm) ?? false;
}

export function permissionsForReports(role, opts) {
  if (opts?.isPlatformAdmin) return REPORTS_PERM_KEYS.slice();
  return REPORTS_MATRIX[role] ?? [];
}

export function reportsCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _REPORTS_SETS[role]?.has(p));
}

export function reportsCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _REPORTS_SETS[role]?.has(p));
}
