/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/service v2.7.1 — service-module permission slice (runtime ESM). */

export const SERVICE_PERM_KEYS = ['service.view', 'service.view_commercials', 'service.create', 'service.close', 'service.reopen', 'service.record_tests', 'service.do_work'];
export const SERVICE_PERMISSIONS = [{"key":"service.view","module":"service","label":"View maintenance","description":"See work orders, faults, and scheduled maintenance.","roles":["manager","supervisor","employee","apprentice"]},{"key":"service.view_commercials","module":"service","label":"See job pricing","description":"See what a job is worth — its price and contract value. Kept separate from viewing maintenance so people can do the work without seeing the money.","roles":["manager","supervisor"]},{"key":"service.create","module":"service","label":"Raise work orders","description":"Raise a new work order or report a fault.","roles":["manager","supervisor"]},{"key":"service.close","module":"service","label":"Close work orders","description":"Mark a work order as finished.","roles":["manager","supervisor"]},{"key":"service.reopen","module":"service","label":"Reopen a work order","description":"Reopen a work order that was already closed. Kept to a small group so the activity log stays meaningful.","roles":["manager","supervisor"]},{"key":"service.record_tests","module":"service","label":"Log calibration results","description":"Record calibration or test results against a piece of equipment.","roles":["manager","supervisor"]},{"key":"service.do_work","module":"service","label":"Carry out and record work","description":"Run test procedures and record their results, and raise an on-site check, in EQ Service.","roles":["manager","supervisor","employee"]}];

/** Per-role grants within the service module. */
export const SERVICE_MATRIX = {
  "manager": [
    "service.view",
    "service.view_commercials",
    "service.create",
    "service.close",
    "service.reopen",
    "service.record_tests",
    "service.do_work"
  ],
  "supervisor": [
    "service.view",
    "service.view_commercials",
    "service.create",
    "service.close",
    "service.reopen",
    "service.record_tests",
    "service.do_work"
  ],
  "employee": [
    "service.view",
    "service.do_work"
  ],
  "apprentice": [
    "service.view"
  ],
  "labour_hire": [],
  "subcontractor": []
};

const _SERVICE_SETS = Object.fromEntries(
  Object.keys(SERVICE_MATRIX).map((r) => [r, new Set(SERVICE_MATRIX[r])]),
);

export function serviceCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _SERVICE_SETS[role]?.has(perm) ?? false;
}

export function permissionsForService(role, opts) {
  if (opts?.isPlatformAdmin) return SERVICE_PERM_KEYS.slice();
  return SERVICE_MATRIX[role] ?? [];
}

export function serviceCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _SERVICE_SETS[role]?.has(p));
}

export function serviceCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _SERVICE_SETS[role]?.has(p));
}
