/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/service v2.5.1 — service-module permission slice (runtime ESM). */

export const SERVICE_PERM_KEYS = ['service.view', 'service.create', 'service.close'];
export const SERVICE_PERMISSIONS = [{"key":"service.view","module":"service","label":"View maintenance","description":"View the Service CMMS (work orders, defects, PPM).","roles":["manager","supervisor","employee","apprentice"]},{"key":"service.create","module":"service","label":"Raise work orders","description":"Create a work order or defect.","roles":["manager","supervisor"]},{"key":"service.close","module":"service","label":"Close work orders","description":"Close / resolve a work order.","roles":["manager","supervisor"]}];

/** Per-role grants within the service module. */
export const SERVICE_MATRIX = {
  "manager": [
    "service.view",
    "service.create",
    "service.close"
  ],
  "supervisor": [
    "service.view",
    "service.create",
    "service.close"
  ],
  "employee": [
    "service.view"
  ],
  "apprentice": [
    "service.view"
  ],
  "labour_hire": [],
  "subcontractor": []
};

const _SERVICE_SETS = Object.fromEntries(
  Object.keys(SERVICE_MATRIX).map((r) => [r, new Set(SERVICE_MATRIX[r])]),
);

export function serviceCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _SERVICE_SETS[role]?.has(perm) ?? false;
}

export function permissionsForService(role, opts) {
  if (opts?.isPlatformAdmin) return SERVICE_PERM_KEYS.slice();
  return SERVICE_MATRIX[role] ?? [];
}

export function serviceCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _SERVICE_SETS[role]?.has(p));
}

export function serviceCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _SERVICE_SETS[role]?.has(p));
}
