/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/service v2.5.3 — service-module permission slice (runtime ESM). */

export const SERVICE_PERM_KEYS = ['service.view', 'service.view_commercials', 'service.create', 'service.close', 'service.reopen', 'service.record_tests'];
export const SERVICE_PERMISSIONS = [{"key":"service.view","module":"service","label":"View maintenance","description":"View the Service CMMS (work orders, defects, PPM).","roles":["manager","supervisor","employee","apprentice"]},{"key":"service.view_commercials","module":"service","label":"See job pricing","description":"See job pricing / contract value on a work order. Split out of service.view. Manager + supervisor only (2026-07-16 access-model cluster 1).","roles":["manager","supervisor"]},{"key":"service.create","module":"service","label":"Raise work orders","description":"Create a work order or defect.","roles":["manager","supervisor"]},{"key":"service.close","module":"service","label":"Close work orders","description":"Close / resolve a work order.","roles":["manager","supervisor"]},{"key":"service.reopen","module":"service","label":"Reopen a work order","description":"Reopen a closed work order. Irreversible-adjacent verb, kept with a named few so the audit log reads clean (2026-07-17 access-model cluster 3).","roles":["manager","supervisor"]},{"key":"service.record_tests","module":"service","label":"Log calibration results","description":"Log calibration / test results against an asset. Matches equipment.edit's manager+supervisor tier (2026-07-17 access-model cluster 3).","roles":["manager","supervisor"]}];

/** Per-role grants within the service module. */
export const SERVICE_MATRIX = {
  "manager": [
    "service.view",
    "service.view_commercials",
    "service.create",
    "service.close",
    "service.reopen",
    "service.record_tests"
  ],
  "supervisor": [
    "service.view",
    "service.view_commercials",
    "service.create",
    "service.close",
    "service.reopen",
    "service.record_tests"
  ],
  "employee": [
    "service.view"
  ],
  "apprentice": [
    "service.view"
  ],
  "labour_hire": [],
  "subcontractor": []
};

const _SERVICE_SETS = Object.fromEntries(
  Object.keys(SERVICE_MATRIX).map((r) => [r, new Set(SERVICE_MATRIX[r])]),
);

export function serviceCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _SERVICE_SETS[role]?.has(perm) ?? false;
}

export function permissionsForService(role, opts) {
  if (opts?.isPlatformAdmin) return SERVICE_PERM_KEYS.slice();
  return SERVICE_MATRIX[role] ?? [];
}

export function serviceCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _SERVICE_SETS[role]?.has(p));
}

export function serviceCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _SERVICE_SETS[role]?.has(p));
}
