/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/service v2.0.0 — service-module permission slice.
 * Import from "@eq-solutions/roles/service" for typed service.* perms only.
 * Full 30-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire';

export type ServicePermKey = 'service.view' | 'service.create' | 'service.close';
export const SERVICE_PERM_KEYS: readonly ServicePermKey[] = ['service.view', 'service.create', 'service.close'];
export const SERVICE_PERMISSIONS = [{"key":"service.view","module":"service","description":"View the Service CMMS (work orders, defects, PPM).","roles":["manager","supervisor","employee","apprentice"]},{"key":"service.create","module":"service","description":"Create a work order or defect.","roles":["manager","supervisor"]},{"key":"service.close","module":"service","description":"Close / resolve a work order.","roles":["manager","supervisor"]}] as const;

/** Per-role grants within the service module. */
export const SERVICE_MATRIX: Record<EqRole, readonly ServicePermKey[]> = {
  "manager": [
    "service.view",
    "service.create",
    "service.close"
  ],
  "supervisor": [
    "service.view",
    "service.create",
    "service.close"
  ],
  "employee": [
    "service.view"
  ],
  "apprentice": [
    "service.view"
  ],
  "labour_hire": []
};

const _SERVICE_SETS: Record<EqRole, Set<ServicePermKey>> = Object.fromEntries(
  (Object.keys(SERVICE_MATRIX) as EqRole[]).map((r) => [r, new Set(SERVICE_MATRIX[r])]),
) as Record<EqRole, Set<ServicePermKey>>;

export function serviceCan(role: EqRole, perm: ServicePermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _SERVICE_SETS[role]?.has(perm) ?? false;
}

export function permissionsForService(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly ServicePermKey[] {
  if (opts?.isPlatformAdmin) return SERVICE_PERM_KEYS.slice();
  return SERVICE_MATRIX[role] ?? [];
}

export function serviceCanAny(role: EqRole, perms: readonly ServicePermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _SERVICE_SETS[role]?.has(p));
}

export function serviceCanAll(role: EqRole, perms: readonly ServicePermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _SERVICE_SETS[role]?.has(p));
}
