/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/tender v2.7.3 — tender-module permission slice (runtime ESM). */

export const TENDER_PERM_KEYS = ['tender.view'];
export const TENDER_PERMISSIONS = [{"key":"tender.view","module":"tender","label":"View tenders","description":"See tenders and their pipeline stage, including estimated value.","roles":["manager","supervisor"]}];

/** Per-role grants within the tender module. */
export const TENDER_MATRIX = {
  "manager": [
    "tender.view"
  ],
  "supervisor": [
    "tender.view"
  ],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _TENDER_SETS = Object.fromEntries(
  Object.keys(TENDER_MATRIX).map((r) => [r, new Set(TENDER_MATRIX[r])]),
);

export function tenderCan(role, perm, opts) {
  if (opts?.isPlatformAdmin) return true;
  return _TENDER_SETS[role]?.has(perm) ?? false;
}

export function permissionsForTender(role, opts) {
  if (opts?.isPlatformAdmin) return TENDER_PERM_KEYS.slice();
  return TENDER_MATRIX[role] ?? [];
}

export function tenderCanAny(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _TENDER_SETS[role]?.has(p));
}

export function tenderCanAll(role, perms, opts) {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _TENDER_SETS[role]?.has(p));
}
