/* GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`. */
/* @eq-solutions/roles/tender v2.7.3 — tender-module permission slice.
 * Import from "@eq-solutions/roles/tender" for typed tender.* perms only.
 * Full 61-perm matrix lives in the root "@eq-solutions/roles" entry. */

/** EqRole — inlined so this module file has zero imports. */
export type EqRole = 'manager' | 'supervisor' | 'employee' | 'apprentice' | 'labour_hire' | 'subcontractor';

export type TenderPermKey = 'tender.view';
export const TENDER_PERM_KEYS: readonly TenderPermKey[] = ['tender.view'];
export const TENDER_PERMISSIONS = [{"key":"tender.view","module":"tender","label":"View tenders","description":"See tenders and their pipeline stage, including estimated value.","roles":["manager","supervisor"]}] as const;

/** Per-role grants within the tender module. */
export const TENDER_MATRIX: Record<EqRole, readonly TenderPermKey[]> = {
  "manager": [
    "tender.view"
  ],
  "supervisor": [
    "tender.view"
  ],
  "employee": [],
  "apprentice": [],
  "labour_hire": [],
  "subcontractor": []
};

const _TENDER_SETS: Record<EqRole, Set<TenderPermKey>> = Object.fromEntries(
  (Object.keys(TENDER_MATRIX) as EqRole[]).map((r) => [r, new Set(TENDER_MATRIX[r])]),
) as Record<EqRole, Set<TenderPermKey>>;

export function tenderCan(role: EqRole, perm: TenderPermKey, opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return _TENDER_SETS[role]?.has(perm) ?? false;
}

export function permissionsForTender(role: EqRole, opts?: { isPlatformAdmin?: boolean }): readonly TenderPermKey[] {
  if (opts?.isPlatformAdmin) return TENDER_PERM_KEYS.slice();
  return TENDER_MATRIX[role] ?? [];
}

export function tenderCanAny(role: EqRole, perms: readonly TenderPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.some((p) => _TENDER_SETS[role]?.has(p));
}

export function tenderCanAll(role: EqRole, perms: readonly TenderPermKey[], opts?: { isPlatformAdmin?: boolean }): boolean {
  if (opts?.isPlatformAdmin) return true;
  return perms.every((p) => _TENDER_SETS[role]?.has(p));
}
