// GENERATED by build.mjs from roles/model.json — do not edit. Run `npm run build`.
// @eq-solutions/roles v2.6.0 — canonical EQ 6-tier role model + permission matrix (Dart).
// Mirrors roles.ts / roles.js exactly. Single source of truth across every EQ
// surface (Shell, Field, Service, Cards, Quotes). Identity (role) is separate
// from billing (tier) and from the isPlatformAdmin override.
//
// Requires Dart 2.17+ (enhanced enums — EqRole.value carries the exact wire
// string read from JWT app_metadata.eq_role). No external package dependency.

/// Canonical EQ role. `.value` is the exact wire string (JWT app_metadata.eq_role).
enum EqRole {
  manager('manager', 'Manager', 1, 'Full access. Manages people and access groups, undoes changes, deletes records, approves quotes, and sees every report.'),
  supervisor('supervisor', 'Supervisor', 2, 'Runs the day-to-day. Views and edits records, runs and confirms imports, manages workers, licences, rosters and dispatch, creates quotes, and sees cost, margin, rates and supplier logins. Cannot manage user accounts, open reports, undo changes, or delete records.'),
  employee('employee', 'Employee', 3, 'Everyday staff access. Views records, quotes, maintenance, equipment and field information, and can start an import. Cannot see personal details, hours, licences, cost or margin.'),
  apprentice('apprentice', 'Apprentice', 4, 'Read-only across records, maintenance, equipment and field information. Can see imports but not start one, and cannot view quotes.'),
  labourHire('labour_hire', 'Labour Hire', 5, 'Agency worker. Sees field information and the equipment list, nothing else.'),
  subcontractor('subcontractor', 'Subcontractor', 6, 'External trade engaged for a job, not an agency worker. Sees field information only.');

  const EqRole(this.value, this.label, this.rank, this.description);

  /// Wire value — matches the DB enum / JWT claim exactly (e.g. 'labour_hire').
  final String value;
  /// Short plain-English name for admin UIs.
  final String label;
  final int rank;
  final String description;

  /// Parse a wire role string (JWT app_metadata.eq_role). Returns null for unknown.
  static EqRole? fromValue(String? value) {
    for (final r in EqRole.values) {
      if (r.value == value) return r;
    }
    return null;
  }
}

const List<String> kTiers = ['trial', 'standard', 'advanced', 'enterprise'];

/// Field on the user/JWT that, when true, grants every permission across every tenant.
const String kPlatformAdminField = 'is_platform_admin';

/// Permission metadata. `deprecated` (if set) explains why + the replacement —
/// still enforced/emitted, just don't grant it to new consumers.
class PermissionMeta {
  const PermissionMeta(this.key, this.module, this.label, this.description, this.roles, {this.deprecated});
  final String key;
  final String module;
  final String label;
  final String description;
  final Set<EqRole> roles;
  final String? deprecated;
}

const List<PermissionMeta> kPermissions = [
  PermissionMeta('admin.list_users', 'admin', 'View users', 'See everyone who can sign in to your organisation, with their role and status.', {EqRole.manager}),
  PermissionMeta('admin.invite_user', 'admin', 'Invite users', 'Send someone an invitation to join and set up their sign-in.', {EqRole.manager}),
  PermissionMeta('admin.edit_user', 'admin', 'Edit users', 'Change someone\'s role, name, or contact details.', {EqRole.manager}),
  PermissionMeta('admin.deactivate_user', 'admin', 'Deactivate users', 'Switch off someone’s access so they can no longer sign in. Their records are kept.', {EqRole.manager}),
  PermissionMeta('admin.review_cards', 'admin', 'Review onboarding', 'Review and approve the details new workers submit when they join — licences, contact details, and documents.', {EqRole.manager}),
  PermissionMeta('admin.manage_groups', 'admin', 'Manage access groups', 'Create access groups and choose who belongs to them. Groups add permissions on top of someone’s role.', {EqRole.manager}),
  PermissionMeta('audit.view', 'audit', 'View activity log', 'See what changed, who changed it, and when.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('audit.rollback', 'audit', 'Undo changes', 'Reverse a change shown in the activity log, putting the record back as it was.', {EqRole.manager}),
  PermissionMeta('entity.view', 'entity', 'View records', 'See customers, sites, contacts, and assets. Personal contact details are controlled separately.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice}),
  PermissionMeta('entity.view_pii', 'entity', 'See personal details', 'See someone’s phone number, date of birth, and emergency contact. Kept separate from viewing records so people can look up a customer or site without seeing personal information.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('entity.create', 'entity', 'Add records', 'Add a new customer, site, contact, or asset.', {EqRole.manager}),
  PermissionMeta('entity.edit', 'entity', 'Edit records', 'Change the details on an existing customer, site, contact, or asset.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('entity.delete', 'entity', 'Delete records', 'Permanently remove a customer, site, contact, or asset. This cannot be undone.', {EqRole.manager}),
  PermissionMeta('entity.manage_activation', 'entity', 'Show records in Field & Service', 'Choose whether a site or customer appears in EQ Field and EQ Service.', {EqRole.manager}),
  PermissionMeta('intake.view', 'intake', 'View imports', 'See imports that have been started and how they went.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice}),
  PermissionMeta('intake.import', 'intake', 'Start an import', 'Upload a spreadsheet, match its columns, and check it for errors — without saving anything yet.', {EqRole.manager, EqRole.supervisor, EqRole.employee}),
  PermissionMeta('intake.commit', 'intake', 'Confirm an import', 'Save a checked import into your live records. This overwrites existing data and cannot be undone.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('equipment.view', 'equipment', 'View equipment', 'See the plant and equipment list, including calibration dates.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice, EqRole.labourHire}),
  PermissionMeta('equipment.edit', 'equipment', 'Edit equipment', 'Add equipment, change its details, or update calibration dates.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('reports.view', 'reports', 'View reports', 'Open the management reports.', {EqRole.manager}),
  PermissionMeta('reports.view_financial', 'reports', 'See financial reports', 'See reports that include revenue, cost, and margin figures.', {EqRole.manager}),
  PermissionMeta('reports.upload', 'reports', 'Upload reports', 'Upload a source file that reports are built from.', {EqRole.manager}),
  PermissionMeta('reports.generate_briefing', 'reports', 'Generate AI briefing', 'Produce the AI-written summary of recent activity.', {EqRole.manager}),
  PermissionMeta('cards.view', 'cards', 'Open Cards', 'Open the worker onboarding app.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice}, deprecated: 'No longer used. EQ Cards is switched on for a whole organisation rather than per person. Existing settings still work — do not apply this to anyone new.'),
  PermissionMeta('cards.onboard', 'cards', 'Submit onboarding', 'Fill in or manage a worker’s onboarding details.', {EqRole.manager, EqRole.supervisor}, deprecated: 'No longer used — “Review onboarding” does this job. Existing settings still work — do not apply this to anyone new.'),
  PermissionMeta('service.view', 'service', 'View maintenance', 'See work orders, faults, and scheduled maintenance.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice}),
  PermissionMeta('service.view_commercials', 'service', 'See job pricing', 'See what a job is worth — its price and contract value. Kept separate from viewing maintenance so people can do the work without seeing the money.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('service.create', 'service', 'Raise work orders', 'Raise a new work order or report a fault.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('service.close', 'service', 'Close work orders', 'Mark a work order as finished.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('service.reopen', 'service', 'Reopen a work order', 'Reopen a work order that was already closed. Kept to a small group so the activity log stays meaningful.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('service.record_tests', 'service', 'Log calibration results', 'Record calibration or test results against a piece of equipment.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('field.view', 'field', 'View field information', 'See staff, licences, availability, and job assignments in EQ Field.', {EqRole.manager, EqRole.supervisor, EqRole.employee, EqRole.apprentice, EqRole.labourHire, EqRole.subcontractor}),
  PermissionMeta('field.view_hours', 'field', 'See timesheets & hours', 'See the hours workers have logged. Kept separate because hours affect pay.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('field.view_licences', 'field', 'See worker licences', 'See workers’ licences and tickets, and whether they are current.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('field.view_rates', 'field', 'See charge rates', 'See what labour-hire workers are charged out at.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('field.dispatch', 'field', 'Dispatch staff', 'Send staff to jobs and shifts.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('field.manage_roster', 'field', 'Build & edit the roster', 'Build and change the crew roster. Separate from day-to-day dispatch because it sets the plan rather than following it.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('field.manage_licences', 'field', 'Manage worker licences', 'Add a worker’s licence or confirm you have sighted it. This is a sign-off — it records that someone checked.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('field.manage_labour_hire', 'field', 'Manage labour-hire companies', 'Add or change the labour-hire companies you use and what they charge.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('field.manage_people', 'field', 'Add / remove / edit workers', 'Add a worker, change their details, remove or restore them, and reset their PIN.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('quotes.view', 'quotes', 'View quotes', 'See quotes and their status. Cost and margin are controlled separately.', {EqRole.manager, EqRole.supervisor, EqRole.employee}),
  PermissionMeta('quotes.create', 'quotes', 'Create quotes', 'Write a new quote or change an existing one.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('quotes.approve', 'quotes', 'Approve quotes', 'Approve a quote and send it to the customer.', {EqRole.manager}),
  PermissionMeta('ops.view_rates', 'ops', 'View rates & pricing setup', 'See what labour-hire agencies charge, and open Setup — where pricing, the rate library, quote templates, and estimators are configured.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('ops.view_margins', 'ops', 'See cost & margin', 'See what a job costs and what you make on it. Kept separate from viewing quotes so people can work on a quote without seeing the margin.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('ops.manage_rates', 'ops', 'Manage rates & pricing setup', 'Add, import, or change labour-hire rate cards and the pricing setup.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('ops.create_job', 'ops', 'Convert quote to a job', 'Turn an accepted quote into a numbered job. Job numbers are entered by hand, so this is a deliberate commitment step.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('ops.view_suppliers', 'ops', 'View suppliers directory', 'See the list of trade suppliers, wholesalers, and hire companies.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('ops.manage_suppliers', 'ops', 'Manage suppliers directory', 'Add, change, or remove entries in the suppliers list.', {EqRole.manager, EqRole.supervisor}),
  PermissionMeta('ops.view_supplier_credentials', 'ops', 'See supplier login/password', 'See the account login and password saved against a supplier. Kept separate so people can use the supplier list without seeing stored passwords.', {EqRole.manager, EqRole.supervisor}),
];

/// Per-role permission grants. No inheritance — every grant is explicit.
final Map<EqRole, Set<String>> kMatrix = {
    EqRole.manager: ['admin.list_users', 'admin.invite_user', 'admin.edit_user', 'admin.deactivate_user', 'admin.review_cards', 'admin.manage_groups', 'audit.view', 'audit.rollback', 'entity.view', 'entity.view_pii', 'entity.create', 'entity.edit', 'entity.delete', 'entity.manage_activation', 'intake.view', 'intake.import', 'intake.commit', 'equipment.view', 'equipment.edit', 'reports.view', 'reports.view_financial', 'reports.upload', 'reports.generate_briefing', 'cards.view', 'cards.onboard', 'service.view', 'service.view_commercials', 'service.create', 'service.close', 'service.reopen', 'service.record_tests', 'field.view', 'field.view_hours', 'field.view_licences', 'field.view_rates', 'field.dispatch', 'field.manage_roster', 'field.manage_licences', 'field.manage_labour_hire', 'field.manage_people', 'quotes.view', 'quotes.create', 'quotes.approve', 'ops.view_rates', 'ops.view_margins', 'ops.manage_rates', 'ops.create_job', 'ops.view_suppliers', 'ops.manage_suppliers', 'ops.view_supplier_credentials'].toSet(),
    EqRole.supervisor: ['audit.view', 'entity.view', 'entity.view_pii', 'entity.edit', 'intake.view', 'intake.import', 'intake.commit', 'equipment.view', 'equipment.edit', 'cards.view', 'cards.onboard', 'service.view', 'service.view_commercials', 'service.create', 'service.close', 'service.reopen', 'service.record_tests', 'field.view', 'field.view_hours', 'field.view_licences', 'field.view_rates', 'field.dispatch', 'field.manage_roster', 'field.manage_licences', 'field.manage_labour_hire', 'field.manage_people', 'quotes.view', 'quotes.create', 'ops.view_rates', 'ops.view_margins', 'ops.manage_rates', 'ops.create_job', 'ops.view_suppliers', 'ops.manage_suppliers', 'ops.view_supplier_credentials'].toSet(),
    EqRole.employee: ['entity.view', 'intake.view', 'intake.import', 'equipment.view', 'cards.view', 'service.view', 'field.view', 'quotes.view'].toSet(),
    EqRole.apprentice: ['entity.view', 'intake.view', 'equipment.view', 'cards.view', 'service.view', 'field.view'].toSet(),
    EqRole.labourHire: ['equipment.view', 'field.view'].toSet(),
    EqRole.subcontractor: ['field.view'].toSet(),
};

/// Does this role hold this permission? isPlatformAdmin short-circuits to true.
bool can(EqRole role, String perm, {bool isPlatformAdmin = false}) {
  if (isPlatformAdmin) return true;
  return kMatrix[role]?.contains(perm) ?? false;
}

/// All permissions a role holds (platform admins hold every key).
Set<String> permissionsFor(EqRole role, {bool isPlatformAdmin = false}) {
  if (isPlatformAdmin) return kPermissions.map((p) => p.key).toSet();
  return kMatrix[role] ?? <String>{};
}

final Map<String, String> _kPermLabels = {
  for (final p in kPermissions) p.key: p.label,
};
/// Plain-English label for a permission key — what a non-technical manager reads.
String? labelFor(String perm) => _kPermLabels[perm];

/// Canonical starter security-group template — an ADDITIVE bundle of extra
/// perms on top of a user's base role. Not a role.
class DefaultGroup {
  const DefaultGroup(this.key, this.name, this.description, this.perms);
  final String key;
  final String name;
  final String description;
  final List<String> perms;
}

const List<DefaultGroup> kDefaultGroups = [
  DefaultGroup('equipment_editors', 'Equipment editors', 'Edit the plant & equipment list and calibration details. Add people here who maintain equipment but whose role normally only lets them view it.', ['equipment.view', 'equipment.edit']),
  DefaultGroup('report_viewers', 'Report viewers', 'View GM reports without being made a manager. Add supervisors or leads here who need to read reports.', ['reports.view']),
  DefaultGroup('project_managers', 'Project Managers', 'Manage users, review Cards onboarding, and view the audit log without full manager admin rights. Promoted from a tenant-specific group (originally SKS) once it proved to be a common cross-cutting need, not a one-off.', ['admin.list_users', 'admin.edit_user', 'admin.review_cards', 'audit.view'])
];

/// Combine a role's base grants with EXTRA perms from security-group
/// memberships into the effective set used for a UI/authZ decision.
/// isPlatformAdmin short-circuits to every permission. revokes (reserved for
/// future per-user denials) is applied last, deny-wins.
Set<String> resolveEffectivePermissions({
  required EqRole role,
  Set<String> groupPerms = const {},
  bool isPlatformAdmin = false,
  Set<String> revokes = const {},
}) {
  if (isPlatformAdmin) return kPermissions.map((p) => p.key).toSet();
  final permKeys = kPermissions.map((p) => p.key).toSet();
  final granted = <String>{...(kMatrix[role] ?? <String>{})};
  for (final p in groupPerms) {
    if (permKeys.contains(p)) granted.add(p);
  }
  granted.removeAll(revokes);
  return granted;
}

/// EQ Service (CMMS) tenant_members.role -> canonical EqRole. super_admin maps to a tenant-scoped manager (NOT is_platform_admin); supervisor is a direct match; technician is an employee; read_only is a read-mostly apprentice.
const Map<String, EqRole> kServiceRoleMap = {
  'super_admin': EqRole.manager,
  'admin': EqRole.manager,
  'supervisor': EqRole.supervisor,
  'technician': EqRole.employee,
  'read_only': EqRole.apprentice,
};

/// Map a service role onto canonical EqRole. Returns null for unknown input.
EqRole? fromServiceRole(String? role) => kServiceRoleMap[role];
